### ISSUE TITLE
when setting path like  let  path = Platform.select({       ios: 'wangyisong.m4a',       android: 'wangyisong.mp4',     });

### ISSUE THREAD

**Issue by z5614036** [dooboolab/react-native-audio-recorder-player#10]
return  is undefined  in android 4.4

**Comment by dooboolab** [comment]
@z5614036 Try to use like below. Android doen't give permission first level of your directory.
```
    const path = Platform.select({
      ios: 'hello.m4a',
      android: 'sdcard/hello.mp4',  // use `some dir name in front of your actual file name in android.
    });
    const uri = await this.audioRecorderPlayer.startRecorder(path);
    this.audioRecorderPlayer.addRecordBackListener((e) => {
      this.setState({
        recordSecs: e.current_position,
        recordTime: this.audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
      });
      return;
    });
```

I've provided this in Example project.

**Comment by abdulrahman18** [comment]
@hyochan I am also using same like this.
 const path = Platform.select({
      ios: 'hello.m4a',
      android: 'sdcard/hello.mp4',  // use `some dir name in front of your actual file name in android.
    });
    const uri = await this.audioRecorderPlayer.startRecorder(path);


After stop the recorder, I didn't get the uri in android devices.Can you help me?
