### ISSUE TITLE
Pause function for recorder

### ISSUE THREAD

**Issue by avoloshko** [dooboolab/react-native-audio-recorder-player#116]
### Expected behavior
should allow to pause / resume recorder

### Steps to reprodue the behabior

**Comment by hyochan** [comment]
It's already there please read the doc. `pausePlayer`, and `resumePlayer`.

**Comment by umang-simform** [comment]
@hyochan  I think here @avoloshko  Is asking for a pause/resume feature for recorder not player

**Comment by hyochan** [comment]
When paused, it will automatically resume it when start again

**Comment by avoloshko** [comment]
> When paused, it will automatically resume it when start again

Was it fixed/implemented? A year ago, the feature did not work.

**Comment by hyochan** [comment]
@avoloshko Below is a working movie which is an example project.

[20201025_202858.zip](https://github.com/dooboolab/react-native-audio-recorder-player/files/5434641/20201025_202858.zip)

**Comment by hyochan** [comment]
@avoloshko @umang-simform You can try `3.0.+` version for this feature. Note that the downside is that you now require `minSdk` for `24` in `Android`.
