### ISSUE TITLE
The recording time is different from the playing time

### ISSUE THREAD

**Issue by ghoudi01** [dooboolab/react-native-audio-recorder-player#117]

**Comment by hyochan** [comment]
How is it different? Please provide an example that can help me debugging.

**Comment by thanhgiangleo** [comment]
when I record for a long time (30 mins in my case), the recorded time is stopped at 30:00, but when I play the playback, it plays longer that 30:00 (maybe 30:14, sometimes it lasts more).
Sorry there is no example code, but that's the idea.

**Comment by sarafhbk** [comment]
this issue is not yet fixed, does anyone knows the solution?
