### ISSUE TITLE
Not saving file when stopRecording()

### ISSUE THREAD

**Issue by davidcantonnoteges** [dooboolab/react-native-audio-recorder-player#12]
Version 2.0.8

iOS

Save file audio.m4a 

Not saving file, i search it by browsing in the path, and with RNFS seaching in the path, system cant find the file: The file “sound.m4a” couldn’t be opened because there is no such file.

Following the example

**Comment by dooboolab** [comment]
@davidcantonnoteges 
```
const result = await this.audioRecorderPlayer.stopRecorder();
```
the actual system uri should be returned here. Check this.

**Comment by davidcantonnoteges** [comment]
Ok, now i can get the file, thanks. But the audio always have 1 second, and 36KB, the file is moved when finish or removed by the system¿

**Comment by dooboolab** [comment]
@davidcantonnoteges File won't be removed automatically unless you overwrite it. You may check your code if there is any overwriting.
