### ISSUE TITLE
seekToPlayer in milliseconds

### ISSUE THREAD

**Issue by poormohammadi** [dooboolab/react-native-audio-recorder-player#125]
I want to use seekToPlayer method in order to move to a non-integer second for example:
seekToPlayer(1.684)
It seems to be an unsupported format.
So, how can I seek to a desire time?

**Comment by hyochan** [comment]
I'll be back

**Comment by hyochan** [comment]
@poormohammadi White `android` supports `millis`, `ios` doesn't support this yet according to [doc](https://developer.apple.com/documentation/avfoundation/avaudioplayer/1387297-currenttime). I'll close this for now but please reopen when you think this should be improved.
