### ISSUE TITLE
Error with Pause

### ISSUE THREAD

**Issue by camiloibarrayepes** [dooboolab/react-native-audio-recorder-player#13]
when using the pause method the application hangs or gets very slow, the only option is to play and select stop, but the pause option is very necessary,

**Comment by dooboolab** [comment]
@camiloibarrayepes Have you tried the example project? I've already tested `pause` functionality before publishing. Could you share some of your experience or codes?

**Comment by abhishektiwari-kiwi** [comment]
Any update on this?
