### ISSUE TITLE
How to have multiple audio Plays Like Whastapp Audio Messages?

### ISSUE THREAD

**Issue by osamausmani** [dooboolab/react-native-audio-recorder-player#130]
### Version of react-native-audio-recorder-player
2.4.3
### Platforms you faced the error (IOS or Android or both?)
Both

I have implemented RN audio recorder and player in my Whatsapp Like application. The recording function is working great. But the audio playing function is working one to one at a time. If one audio is playing at a time I can't play any other one. I want if the user tapped on second audio the previous get paused and the second one gets played if the user again tapped the first one audio then the first audio gets played from where it is paused. Actually I needed audio messages similar to the Whatapps.

[My Current Design](https://i.imgur.com/Mrhq9oH.png)

Is this is possible what I am looking for?

**Comment by hyochan** [comment]
Playlist feature is not implemented.

**Comment by RZulfikri** [comment]
here what I did for the cases. cc @osamausmani 

first, create file called AudioManager.js.
```javascript
import AudioRecorderPlayer from 'react-native-audio-recorder-player'

let audioRecorderPlayer = undefined
let currentPath = undefined
let currentCallback = () => { }
let currentPosition = 0

const AUDIO_STATUS = {
  play: 'play',
  begin: 'begin',
  pause: 'pause',
  resume: 'resume',
  stop: 'stop',
}

async function startPlayer(path, callback) {
  console.log({ currentPath, path })

  if (currentPath === undefined) {
    currentPath = path
    currentCallback = callback
  } else if (currentPath !== path) {
    if (audioRecorderPlayer !== undefined) {
      try {
        await stopPlayer()
      } catch (error) {
        console.log('ERROR STOP PLAYER TOP')
      }
    }
    currentPath = path
    currentCallback = callback
  }

  if (audioRecorderPlayer === undefined) {
    audioRecorderPlayer = new AudioRecorderPlayer()
  }

  try {
    const activePath = await audioRecorderPlayer.startPlayer(currentPath);
    console.log({ activePath })
    currentCallback({
      status: (currentPath === path) && (currentPosition > 0) ? AUDIO_STATUS.resume : AUDIO_STATUS.begin
    })
    audioRecorderPlayer.addPlayBackListener(async (e) => {
      if (e.current_position === e.duration) {
        try {
          await stopPlayer()
        } catch (error) {
          console.log('ERROR STOP PLAYER IN LISTENER')
        }
      } else {
        currentPosition = e.current_position
        currentCallback({
          status: AUDIO_STATUS.play,
          data: e
        })
      }
      return
    });
  } catch (error) {
    console.log({ 'ERROR PLAY PLAYER': error })
  }
}

async function pausePlayer() {
  try {
    await audioRecorderPlayer.pausePlayer();
    currentCallback({ status: AUDIO_STATUS.pause })
  } catch (error) {
    console.log({ 'ERROR PAUSE PLAYER': error })
  }
}

async function stopPlayer() {
  const isStop = await audioRecorderPlayer.stopPlayer();
  console.log({ isStop })
  audioRecorderPlayer.removePlayBackListener()
  currentPosition = 0
  currentCallback({ status: AUDIO_STATUS.stop })
  audioRecorderPlayer = undefined
}

export {
  AUDIO_STATUS,
  startPlayer,
  stopPlayer,
  pausePlayer,
}
```

second, use AudioManager.js to to play, stop or pause audio instead of directly called audiRecorderPlayer, look like this:
```javascript
async playAudio() {
    const { localFile } = this.state
    await AudioManager.startPlayer(localFile, (res) => {
      const { status } = res
      switch (status) {
        case AudioManager.AUDIO_STATUS.begin: {
          console.log(('BEGIN AUDIO')
          this.setState({ isPlay: true })
          break
        }
        case AudioManager.AUDIO_STATUS.play: {
          const { current_position, duration } = res.data
          this.setState({ playDuration: current_position })
          break
        }
        case AudioManager.AUDIO_STATUS.pause: {
         console.log('PAUSE AUDIO')
          this.setState({ isPause: true })
          break
        }
        case AudioManager.AUDIO_STATUS.resume: {
          console.log(('RESUME AUDIO')
          this.setState({ isPause: false })
          break
        }
        case AudioManager.AUDIO_STATUS.stop: {
          console.log('STOP AUDIO')
          this.setState({ isPlay: false, isPause: false })
          break
        }
      }
    })
  }

  async pauseAudio() {
    await AudioManager.pausePlayer()
  }
```

**Comment by efstathiosntonas** [comment]
A small bug fix on `stopPlayer` function just in case someone else encounters this:

Previously: 
```
async function stopPlayer() {
  const isStop = await audioRecorderPlayer.stopPlayer();
  console.log({ isStop })
  audioRecorderPlayer.removePlayBackListener()
  currentPosition = 0
  currentCallback({ status: AUDIO_STATUS.stop })
  audioRecorderPlayer = undefined
}

```

fixed: 
```
async function stopPlayer() {
  const isStop = await audioRecorderPlayer.stopPlayer();
  console.log({ isStop })
  audioRecorderPlayer.removePlayBackListener()
  currentPosition = 0
  currentPath = undefined; // <----- added this line
  currentCallback({ status: AUDIO_STATUS.stop })
  audioRecorderPlayer = undefined
}
```

Bug test case:
1. User plays an audio file
2. While the audio still plays exit the chat room (the audio player should stop playing while we exit the chat room)
3. Re-enter the same chat room
4. Try to play the same audio file
5. The slider of the audio message won't move but you can hear sound, this is happening because the `this.setState({ playDuration: current_position })` is not being triggered

**Comment by Somtozech** [comment]
Does anyone have an example using hooks? Same example doesn't work for react hooks

**Comment by Vivaan7** [comment]
> here what I did for the cases. cc @osamausmani
> 
> first, create file called AudioManager.js.
> 
> ```js
> import AudioRecorderPlayer from 'react-native-audio-recorder-player'
> 
> let audioRecorderPlayer = undefined
> let currentPath = undefined
> let currentCallback = () => { }
> let currentPosition = 0
> 
> const AUDIO_STATUS = {
>   play: 'play',
>   begin: 'begin',
>   pause: 'pause',
>   resume: 'resume',
>   stop: 'stop',
> }
> 
> async function startPlayer(path, callback) {
>   console.log({ currentPath, path })
> 
>   if (currentPath === undefined) {
>     currentPath = path
>     currentCallback = callback
>   } else if (currentPath !== path) {
>     if (audioRecorderPlayer !== undefined) {
>       try {
>         await stopPlayer()
>       } catch (error) {
>         console.log('ERROR STOP PLAYER TOP')
>       }
>     }
>     currentPath = path
>     currentCallback = callback
>   }
> 
>   if (audioRecorderPlayer === undefined) {
>     audioRecorderPlayer = new AudioRecorderPlayer()
>   }
> 
>   try {
>     const activePath = await audioRecorderPlayer.startPlayer(currentPath);
>     console.log({ activePath })
>     currentCallback({
>       status: (currentPath === path) && (currentPosition > 0) ? AUDIO_STATUS.resume : AUDIO_STATUS.begin
>     })
>     audioRecorderPlayer.addPlayBackListener(async (e) => {
>       if (e.current_position === e.duration) {
>         try {
>           await stopPlayer()
>         } catch (error) {
>           console.log('ERROR STOP PLAYER IN LISTENER')
>         }
>       } else {
>         currentPosition = e.current_position
>         currentCallback({
>           status: AUDIO_STATUS.play,
>           data: e
>         })
>       }
>       return
>     });
>   } catch (error) {
>     console.log({ 'ERROR PLAY PLAYER': error })
>   }
> }
> 
> async function pausePlayer() {
>   try {
>     await audioRecorderPlayer.pausePlayer();
>     currentCallback({ status: AUDIO_STATUS.pause })
>   } catch (error) {
>     console.log({ 'ERROR PAUSE PLAYER': error })
>   }
> }
> 
> async function stopPlayer() {
>   const isStop = await audioRecorderPlayer.stopPlayer();
>   console.log({ isStop })
>   audioRecorderPlayer.removePlayBackListener()
>   currentPosition = 0
>   currentCallback({ status: AUDIO_STATUS.stop })
>   audioRecorderPlayer = undefined
> }
> 
> export {
>   AUDIO_STATUS,
>   startPlayer,
>   stopPlayer,
>   pausePlayer,
> }
> ```
> 
> second, use AudioManager.js to to play, stop or pause audio instead of directly called audiRecorderPlayer, look like this:
> 
> ```js
> async playAudio() {
>     const { localFile } = this.state
>     await AudioManager.startPlayer(localFile, (res) => {
>       const { status } = res
>       switch (status) {
>         case AudioManager.AUDIO_STATUS.begin: {
>           console.log(('BEGIN AUDIO')
>           this.setState({ isPlay: true })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.play: {
>           const { current_position, duration } = res.data
>           this.setState({ playDuration: current_position })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.pause: {
>          console.log('PAUSE AUDIO')
>           this.setState({ isPause: true })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.resume: {
>           console.log(('RESUME AUDIO')
>           this.setState({ isPause: false })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.stop: {
>           console.log('STOP AUDIO')
>           this.setState({ isPlay: false, isPause: false })
>           break
>         }
>       }
>     })
>   }
> 
>   async pauseAudio() {
>     await AudioManager.pausePlayer()
>   }
> ```

  


@RZulfikri  can you help me to implement how you are using this code in you js screen ??? specially audioManager

**Comment by RZulfikri** [comment]
@Vivaan7  Maybe look like this.

```javascript
import * as AudioManager from './AudioManager'; 

class ABC extends Component {
  // function to play audio
  async playAudio(filePath) {
      await AudioManager.startPlayer(filePath, (res) => {
        const { status } = res
        switch (status) {
          case AudioManager.AUDIO_STATUS.begin: {
            console.log(('BEGIN AUDIO')
            this.setState({ isPlay: true })
            break
          }
          case AudioManager.AUDIO_STATUS.play: {
            const { current_position, duration } = res.data
            this.setState({ playDuration: current_position })
            break
          }
          case AudioManager.AUDIO_STATUS.pause: {
           console.log('PAUSE AUDIO')
            this.setState({ isPause: true })
            break
          }
          case AudioManager.AUDIO_STATUS.resume: {
            console.log(('RESUME AUDIO')
            this.setState({ isPause: false })
            break
          }
          case AudioManager.AUDIO_STATUS.stop: {
            console.log('STOP AUDIO')
            this.setState({ isPlay: false, isPause: false })
            break
          }
        }
      })
    }
  
  // function to pause audio
    async pauseAudio() {
      await AudioManager.pausePlayer()
    }
    
    render() {
       const. {isPlay} = this.state
       return (
          <TouchableOpacity onPress={isPlay ? () => this.pauseAudio() : () => this.playAudio("file://")}>
             <Text>Play/Pause</Text>
          </TouchableOpacity>
       )
    }
}
```

**Comment by Vivaan7** [comment]
**** @RZulfikri  thank you but still fluctuation is there I need same functionalities like what's app , now I play the first clip while first clip is playing I click on second so first will get pause and second will play but after this again when I try to start first clip from that position I get the error  LOG  {"ERROR PAUSE PLAYER": [TypeError: undefined is not an object (evaluating 'audioRecorderPlayer.pausePlayer')]}    

so can you suggest how to manage state or player with global variable or  with help or item's value in list ? I am hurry thank you in advance !

**Comment by Somtozech** [comment]
@Vivaan7 this is what I did. Let's say an audio state for a player is represented like this
```
 {
  isPlaying: false,
  playTime:  '00:02',
  duration: "02:00",
  isPause: false,
};
```
Each audio player has a unique id (which can be the url of the audio you are playing or whatever you choose. The multiple audio player states are stored in a global object (in my case was context api but can be redux or any other state management library you use)
```
const globalObject = {
  'audioPlayer1id': {
    isPlaying: false,
    duration: 0,
    isPause: false,
    playTime: 0
  },
  'audioPlayer2Id': {
    isPlaying: false,
    duration: 0,
    isPause: false,
    playTime: 0
  }
}
```

From you scenario, if the first clip is currently playing and you click on the second clip, what you do is search through the global object, find the clip currently playing, update the state so isPause becomes false, then update the state of the second clip so isPlay becomes true etc.  You can also track the audio player playTime then update the globalObject to have the correct state.

**Comment by Vivaan7** [comment]
@Somtozech okay I am using same thing but may be I have issue while updating state while changing the clip so let me check from my side ... thank you for response ...

**Comment by NhatGinnovations** [comment]
> here what I did for the cases. cc @osamausmani
> 
> first, create file called AudioManager.js.
> 
> ```js
> import AudioRecorderPlayer from 'react-native-audio-recorder-player'
> 
> let audioRecorderPlayer = undefined
> let currentPath = undefined
> let currentCallback = () => { }
> let currentPosition = 0
> 
> const AUDIO_STATUS = {
>   play: 'play',
>   begin: 'begin',
>   pause: 'pause',
>   resume: 'resume',
>   stop: 'stop',
> }
> 
> async function startPlayer(path, callback) {
>   console.log({ currentPath, path })
> 
>   if (currentPath === undefined) {
>     currentPath = path
>     currentCallback = callback
>   } else if (currentPath !== path) {
>     if (audioRecorderPlayer !== undefined) {
>       try {
>         await stopPlayer()
>       } catch (error) {
>         console.log('ERROR STOP PLAYER TOP')
>       }
>     }
>     currentPath = path
>     currentCallback = callback
>   }
> 
>   if (audioRecorderPlayer === undefined) {
>     audioRecorderPlayer = new AudioRecorderPlayer()
>   }
> 
>   try {
>     const activePath = await audioRecorderPlayer.startPlayer(currentPath);
>     console.log({ activePath })
>     currentCallback({
>       status: (currentPath === path) && (currentPosition > 0) ? AUDIO_STATUS.resume : AUDIO_STATUS.begin
>     })
>     audioRecorderPlayer.addPlayBackListener(async (e) => {
>       if (e.current_position === e.duration) {
>         try {
>           await stopPlayer()
>         } catch (error) {
>           console.log('ERROR STOP PLAYER IN LISTENER')
>         }
>       } else {
>         currentPosition = e.current_position
>         currentCallback({
>           status: AUDIO_STATUS.play,
>           data: e
>         })
>       }
>       return
>     });
>   } catch (error) {
>     console.log({ 'ERROR PLAY PLAYER': error })
>   }
> }
> 
> async function pausePlayer() {
>   try {
>     await audioRecorderPlayer.pausePlayer();
>     currentCallback({ status: AUDIO_STATUS.pause })
>   } catch (error) {
>     console.log({ 'ERROR PAUSE PLAYER': error })
>   }
> }
> 
> async function stopPlayer() {
>   const isStop = await audioRecorderPlayer.stopPlayer();
>   console.log({ isStop })
>   audioRecorderPlayer.removePlayBackListener()
>   currentPosition = 0
>   currentCallback({ status: AUDIO_STATUS.stop })
>   audioRecorderPlayer = undefined
> }
> 
> export {
>   AUDIO_STATUS,
>   startPlayer,
>   stopPlayer,
>   pausePlayer,
> }
> ```
> 
> second, use AudioManager.js to to play, stop or pause audio instead of directly called audiRecorderPlayer, look like this:
> 
> ```js
> async playAudio() {
>     const { localFile } = this.state
>     await AudioManager.startPlayer(localFile, (res) => {
>       const { status } = res
>       switch (status) {
>         case AudioManager.AUDIO_STATUS.begin: {
>           console.log(('BEGIN AUDIO')
>           this.setState({ isPlay: true })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.play: {
>           const { current_position, duration } = res.data
>           this.setState({ playDuration: current_position })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.pause: {
>          console.log('PAUSE AUDIO')
>           this.setState({ isPause: true })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.resume: {
>           console.log(('RESUME AUDIO')
>           this.setState({ isPause: false })
>           break
>         }
>         case AudioManager.AUDIO_STATUS.stop: {
>           console.log('STOP AUDIO')
>           this.setState({ isPlay: false, isPause: false })
>           break
>         }
>       }
>     })
>   }
> 
>   async pauseAudio() {
>     await AudioManager.pausePlayer()
>   }
> ```

A small fix in playback listener:
audioRecorderPlayer.addPlayBackListener(async (e) => {
       currentPosition = e.current_position
         currentCallback({
           status: AUDIO_STATUS.play,
           data: e
         })
      if (e.current_position === e.duration) {
        try {
          await stopPlayer()
        } catch (error) {
          console.log('ERROR STOP PLAYER IN LISTENER')
        }
      }
      return
    });

**Comment by balu4131** [comment]
Here also one issues i face is like once a new comment comes then the current playing cannot be paused unless i play another audio

**Comment by vanGalilea** [comment]
Another iteration that might make your life a bit easier.
I've added types and squashed some bugs ;)


Create a `AudioManager.ts` file, this should be its content:
```
import AudioRecorderPlayer, {
  PlayBackType,
} from 'react-native-audio-recorder-player'

type Callback = (args: {status: AudioStatus; data?: PlayBackType}) => void
type Path = string | undefined
export enum AudioStatus {
  PLAYING = 'PLAYING',
  STARTED = 'STARTED',
  PAUSED = 'PAUSED',
  RESUMED = 'RESUMED',
  STOPPED = 'STOPPED',
}

let audioRecorderPlayer: AudioRecorderPlayer | undefined = undefined
let currentPath: Path = undefined
let currentCallback: Callback = () => {}
let currentPosition = 0

export const startPlayer = async (path: string, callback: Callback) => {
  if (currentPath === undefined) {
    currentPath = path
    currentCallback = callback
  } else if (currentPath !== path) {
    if (audioRecorderPlayer !== undefined) {
      await stopPlayer()
    }
    currentPath = path
    currentCallback = callback
  }

  if (audioRecorderPlayer === undefined) {
    audioRecorderPlayer = new AudioRecorderPlayer()
  }

  const shouldBeResumed = currentPath === path && currentPosition > 0

  if (shouldBeResumed) {
    await audioRecorderPlayer.resumePlayer()
    currentCallback({
      status: AudioStatus.RESUMED,
    })
    return
  }

  await audioRecorderPlayer.startPlayer(currentPath)
  currentCallback({
    status: AudioStatus.STARTED,
  })
  audioRecorderPlayer.addPlayBackListener(async e => {
    if (e.currentPosition === e.duration) {
      await stopPlayer()
    } else {
      currentPosition = e.currentPosition
      currentCallback({
        status: AudioStatus.PLAYING,
        data: e,
      })
    }
    return
  })
}

export const pausePlayer = async () => {
  await audioRecorderPlayer?.pausePlayer()
  currentCallback({status: AudioStatus.PAUSED})
}

export const stopPlayer = async () => {
  await audioRecorderPlayer?.stopPlayer()
  audioRecorderPlayer?.removePlayBackListener()
  currentPosition = 0
  currentCallback({status: AudioStatus.STOPPED})
  audioRecorderPlayer = undefined
}
```

You can use it by calling the funcs like this:
```
    setLoadingAudio(true)
    await startPlayer(asset_url, async ({status, data}) => {
      if (status === AudioStatus.STARTED) {
        setLoadingAudio(false)
      } else if (status === AudioStatus.PLAYING) {
        setCurrentPositionSec(data?.currentPosition as number)
        setCurrentDurationSec(data?.duration as number)
      } else if (status === AudioStatus.PAUSED) {
        setPaused(true)
      } else if (status === AudioStatus.RESUMED) {
        setPaused(false)
      } else if (status === AudioStatus.STOPPED) {
        await onStopPlay()
      }
    })
```

**Comment by efstathiosntonas** [comment]
@vanGalilea excellent! Do you mind sharing the bugs you squahed? Thanks

**Comment by balu4131** [comment]
Nice work.

**Comment by luco** [comment]
> Another iteration that might make your life a bit easier. I've added types and squashed some bugs ;)
> 
> Create a `AudioManager.ts` file, this should be its content:
> 
> ```tsx
> import AudioRecorderPlayer, {
>   PlayBackType,
> } from 'react-native-audio-recorder-player'
> 
> type Callback = (args: {status: AudioStatus; data?: PlayBackType}) => void
> type Path = string | undefined
> export enum AudioStatus {
>   PLAYING = 'PLAYING',
>   STARTED = 'STARTED',
>   PAUSED = 'PAUSED',
>   RESUMED = 'RESUMED',
>   STOPPED = 'STOPPED',
> }
> 
> let audioRecorderPlayer: AudioRecorderPlayer | undefined = undefined
> let currentPath: Path = undefined
> let currentCallback: Callback = () => {}
> let currentPosition = 0
> 
> export const startPlayer = async (path: string, callback: Callback) => {
>   if (currentPath === undefined) {
>     currentPath = path
>     currentCallback = callback
>   } else if (currentPath !== path) {
>     if (audioRecorderPlayer !== undefined) {
>       await stopPlayer()
>     }
>     currentPath = path
>     currentCallback = callback
>   }
> 
>   if (audioRecorderPlayer === undefined) {
>     audioRecorderPlayer = new AudioRecorderPlayer()
>   }
> 
>   const shouldBeResumed = currentPath === path && currentPosition > 0
> 
>   if (shouldBeResumed) {
>     await audioRecorderPlayer.resumePlayer()
>     currentCallback({
>       status: AudioStatus.RESUMED,
>     })
>     return
>   }
> 
>   await audioRecorderPlayer.startPlayer(currentPath)
>   currentCallback({
>     status: AudioStatus.STARTED,
>   })
>   audioRecorderPlayer.addPlayBackListener(async e => {
>     if (e.currentPosition === e.duration) {
>       await stopPlayer()
>     } else {
>       currentPosition = e.currentPosition
>       currentCallback({
>         status: AudioStatus.PLAYING,
>         data: e,
>       })
>     }
>     return
>   })
> }
> 
> export const pausePlayer = async () => {
>   await audioRecorderPlayer?.pausePlayer()
>   currentCallback({status: AudioStatus.PAUSED})
> }
> 
> export const stopPlayer = async () => {
>   await audioRecorderPlayer?.stopPlayer()
>   audioRecorderPlayer?.removePlayBackListener()
>   currentPosition = 0
>   currentCallback({status: AudioStatus.STOPPED})
>   audioRecorderPlayer = undefined
> }
> ```
> 
> You can use it by calling the funcs like this:
> 
> ```tsx
>     setLoadingAudio(true)
>     await startPlayer(asset_url, async ({status, data}) => {
>       if (status === AudioStatus.STARTED) {
>         setLoadingAudio(false)
>       } else if (status === AudioStatus.PLAYING) {
>         setCurrentPositionSec(data?.currentPosition as number)
>         setCurrentDurationSec(data?.duration as number)
>       } else if (status === AudioStatus.PAUSED) {
>         setPaused(true)
>       } else if (status === AudioStatus.RESUMED) {
>         setPaused(false)
>       } else if (status === AudioStatus.STOPPED) {
>         await onStopPlay()
>       }
>     })
> ```

I can't make it to play again after it ended. What's on your `onStopPlay` function?

**Comment by syedumair043** [comment]
PlaybackListeners are not working in this component

```
import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  Alert,
  Platform,
  Dimensions,
  Animated,
  ActivityIndicator,
} from 'react-native';
import { colors } from '../../utils/colors';
import AudioRecorderPlayer from 'react-native-audio-recorder-player';

interface AudioPlayerProps {
  audioUrl: string;
  messageId: string;
  isOwn: boolean;
  isUploading?: boolean;
  onPlayStateChange?: (isPlaying: boolean) => void;
}

const NUM_BARS = 30; // Number of waveform bars, like WhatsApp
const MAX_BAR_HEIGHT = 20; // Maximum height of bars

const AudioPlayer: React.FC<AudioPlayerProps> = ({
  audioUrl,
  messageId,
  isOwn,
  isUploading = false,
  onPlayStateChange,
}) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [duration, setDuration] = useState(0);
  const [currentPosition, setCurrentPosition] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [formattedDuration, setFormattedDuration] = useState('00:00');
  const [formattedCurrentPosition, setFormattedCurrentPosition] = useState('00:00');
  
  // Waveform and seek bar
  const [barHeights, setBarHeights] = useState<number[]>([]);
  const progressAnim = useRef(new Animated.Value(0)).current;
  
  const playListenerRef = useRef<any>(null);

  // Generate random bar heights to mimic waveform
  useEffect(() => {
    const heights = Array.from({ length: NUM_BARS }, () => 
      Math.floor(Math.random() * MAX_BAR_HEIGHT) + 2 // Min height 2 for visibility
    );
    setBarHeights(heights);
  }, []);

  useEffect(() => {
    return () => {
      // Cleanup
      if (playListenerRef.current) {
        AudioRecorderPlayer.removePlayBackListener();
      }
      AudioRecorderPlayer.stopPlayer();
    };
  }, []);

  // Format time helper
  const formatTime = (milliseconds: number): string => {
    const totalSeconds = Math.floor(milliseconds / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  };

  // Handle play/pause
  const handlePlayPause = async () => {
    try {
      if (isPlaying) {
        // Pause
        await AudioRecorderPlayer.pausePlayer();
        setIsPlaying(false);
        onPlayStateChange?.(false);
        progressAnim.stopAnimation();
      } else {
        // Play
        setIsLoading(true);
        await AudioRecorderPlayer.startPlayer(audioUrl);
        
        // Set up listener for playback updates
        playListenerRef.current = AudioRecorderPlayer.addPlayBackListener((e: any) => {
          setCurrentPosition(e.currentPosition);
          setDuration(e.duration);
          setFormattedCurrentPosition(formatTime(e.currentPosition));
          setFormattedDuration(formatTime(e.duration));
          
          // Animate progress
          const progress = e.currentPosition / e.duration || 0;
          Animated.timing(progressAnim, {
            toValue: progress,
            duration: 100,
            useNativeDriver: false,
          }).start();
          
          // Auto-stop when finished
          if (e.currentPosition >= e.duration) {
            setIsPlaying(false);
            setCurrentPosition(0);
            setFormattedCurrentPosition('00:00');
            onPlayStateChange?.(false);
            AudioRecorderPlayer.stopPlayer();
            AudioRecorderPlayer.removePlayBackListener();
            playListenerRef.current = null;
            progressAnim.setValue(0);
          }
        });
        
        setIsPlaying(true);
        setIsLoading(false);
        onPlayStateChange?.(true);
      }
    } catch (error) {
      console.error('Audio playback error:', error);
      Alert.alert('Error', 'Failed to play audio');
      setIsLoading(false);
      setIsPlaying(false);
      onPlayStateChange?.(false);
    }
  };

  // Handle seek
  const handleSeek = async (seekPercentage: number) => {
    const seekTime = duration * seekPercentage;
    try {
      await AudioRecorderPlayer.seekToPlayer(seekTime);
      setCurrentPosition(seekTime);
      setFormattedCurrentPosition(formatTime(seekTime));
      progressAnim.setValue(seekPercentage);
    } catch (error) {
      console.error('Seek error:', error);
    }
  };

  // Render waveform bars
  const renderWaveform = () => {
    const screenWidth = Dimensions.get('window').width;
    const waveformWidth = screenWidth * 0.5; // Approx 50% of screen width
    const barWidth = (waveformWidth / NUM_BARS) - 2; // 2px spacing
    
    return (
      <View style={styles.waveformContainer}>
        {barHeights.map((height, index) => (
          <View
            key={index}
                          style={[
                styles.bar,
                {
                  height,
                  width: barWidth,
                  backgroundColor: isUploading 
                    ? (isOwn ? 'rgba(255, 255, 255, 0.1)' : 'rgba(0, 0, 0, 0.1)')
                    : (isOwn ? 'rgba(255, 255, 255, 0.3)' : 'rgba(0, 0, 0, 0.2)'),
                },
              ]}
          />
        ))}
      </View>
    );
  };

  return (
    <View style={{ height: 80 }}>
      <TouchableOpacity
        style={styles.playButton}
        onPress={handlePlayPause}
        disabled={isLoading || isUploading}
      >
        {isUploading ? (
          <ActivityIndicator size="small" color="#FFFFFF" />
        ) : isLoading ? (
          <Text style={styles.playButtonText}>...</Text>
        ) : isPlaying ? (
          <Text style={styles.playButtonText}>⏸</Text>
        ) : (
          <Text style={styles.playButtonText}>▶</Text>
        )}
      </TouchableOpacity>
      
      {/* Waveform */}
      {renderWaveform()}
      
      {/* Seek Bar */}
      <TouchableOpacity
        style={styles.seekBarContainer}
        onPress={(event) => {
          if (isUploading) return; // Disable seeking during upload
          const { locationX } = event.nativeEvent;
          const screenWidth = Dimensions.get('window').width;
          const waveformWidth = screenWidth * 0.5;
          const seekPercentage = locationX / waveformWidth;
          handleSeek(seekPercentage);
        }}
        activeOpacity={isUploading ? 1 : 0.8}
        disabled={isUploading}
      >
        <View style={[styles.seekBarBackground, isUploading && { opacity: 0.5 }]}>
          <Animated.View
            style={[
              styles.seekBarProgress,
              {
                width: isUploading ? '0%' : progressAnim.interpolate({
                  inputRange: [0, 1],
                  outputRange: ['0%', '100%'],
                }),
              },
            ]}
          />
        </View>
      </TouchableOpacity>
      
      {/* Time Display */}
      <Text style={styles.timeText}>
        {isUploading ? 'Uploading...' : formattedCurrentPosition}
      </Text>
      </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    maxWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  ownContainer: {
    backgroundColor: '#DCF8C6', // WhatsApp green for sent messages
    alignSelf: 'flex-end',
    borderTopRightRadius: 0,
  },
  otherContainer: {
    backgroundColor: '#FFFFFF', // White for received messages
    alignSelf: 'flex-start',
    borderTopLeftRadius: 0,
  },
  playButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#25D366', // WhatsApp green
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  playButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  waveformContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: MAX_BAR_HEIGHT + 4,
    flex: 1,
    marginBottom: 4,
  },
  bar: {
    marginHorizontal: 1,
    borderRadius: 2,
  },
  seekBarContainer: {
    flex: 1,
    height: 4,
    justifyContent: 'center',
  },
  seekBarBackground: {
    height: 4,
    backgroundColor: '#E5E5EA', // Light gray for remaining
    borderRadius: 2,
    overflow: 'hidden',
  },
  seekBarProgress: {
    height: '100%',
    backgroundColor: '#25D366', // WhatsApp green for progress
    borderRadius: 2,
  },
  timeText: {
    fontSize: 12,
    fontWeight: '500',
    color:  '#000000',
    minWidth: 40,
    textAlign: 'right',
  },
});

export default AudioPlayer;
```
