### ISSUE TITLE
startPlayer method does not support absolute local path on iOS

### ISSUE THREAD

**Issue by CochiorasBogdan** [dooboolab/react-native-audio-recorder-player#133]
### Version of react-native-audio-recorder-player
2.4.3
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
The absolute path should be used fol local file playback.
### Actual behavior
The documents directory is added as a string prefix to the passed path parameter.
### Steps to reprodue the behabior

Hello I see in the latest release the [commit](https://github.com/dooboolab/react-native-audio-recorder-player/blob/954b7df2c6724190627917fb4a0145ece969e44c/ios/RNAudioRecorderPlayer.m#L259) was reverted somehwere on the road and I have a bug where I specify an absolute local path with 'file://' extension and the player cannot load the file since it adds the document directory path as a prefix to my absolute path. Also it took a few hours to identify the issue since the error is null on AVAudioPlayer allocation here and it is not thrown to JS: [here](https://github.com/dooboolab/react-native-audio-recorder-player/blob/954b7df2c6724190627917fb4a0145ece969e44c/ios/RNAudioRecorderPlayer.m#L264) the error when the url is bad is the one described [here](https://stackoverflow.com/questions/29088594/osstatus-error-2003334207-when-using-avaudioplayer)
So the playback is kind of broken if you store the full file path because nowhere a full path can be specified, any idea why that change was reverted? Was this intended? I will have to patch the code to the past behavior to function correctly.
Also there are some inconsistencies with how paths are used `NSURL` paths are converted to `absoluteStrings` instead of `path` which return different values please check this example, one returns the `file://` prefix and the other does not:
```
(lldb) po [[NSURL fileURLWithPath:@"/Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a"] path]
/Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a

(lldb) po [[NSURL fileURLWithPath:@"/Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a"] absoluteString]
file:///Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a
```

The same applies to `fileURLWithPath` this does not acceep the `file://` prefix but `URLWithString` does please check the examples below:
```
(lldb) po [NSURL fileURLWithPath:@"/Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a"]
file:///Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a

(lldb) po [NSURL URLWithString:@"file:///Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a"]
file:///Users/cochiorasbogdan/Library/Developer/CoreSimulator/Devices/0728459E-9AA0-4275-B05A-B62F1FA4F592/data/Containers/Data/Application/9064B4F9-8235-4085-908A-B4FA543B11CC/tmp/audio_attch1572007625170.m4a
```
So either the `file://` prefix should be used everywhere and go with the string solution for local paths or path solution and use `path` instead of `absoluteString`. Let me know your thoughs.

**Comment by hyochan** [comment]
If you can give us a nice `PR` with `example` project working with it, I'll consider the update. I've reverted the `PR` because the it seems to break in `example` project. I hope you can also try things in `example` so I can have a runnable example.
