### ISSUE TITLE
Recorded sounds not being heard

### ISSUE THREAD

**Issue by AresDev** [dooboolab/react-native-audio-recorder-player#136]
### Platforms you faced the error (IOS or Android or both?)
Both
### Expected behavior
Reproduce recorded sounds

### Actual behavior
Nothing is heard don't know if it is no recording or not reproducing as expected but shows no errors.
I have the permissions enabled and everything seems normal.

### Steps to reproduce the behavior
Just add your library in fresh react-native project

**Comment by hyochan** [comment]
If you test this in `emulator`, it's expected.

**Comment by AresDev** [comment]
Thanks for your quick answer! first, this was the case but then I've tried in an iPad with the same results, any ideas?

Thank you!

**Comment by hyochan** [comment]
We need minimal reproduction to dig into your problem!
