### ISSUE TITLE
IOS does not play local mp3 files

### ISSUE THREAD

**Issue by janlonden** [dooboolab/react-native-audio-recorder-player#14]
### Version of react-native-audio-recorder-player
2.0.8
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Audio plays
### Actual behavior
Audio does not play
### Steps to reprodue the behabior
Play a local mp3 file where path looks something like: `/Users/[user]/Library/Developer/CoreSimulator/Devices/5555-5555-5555/data/Containers/Data/Application/5555-5555-5555/Documents/tracks/track.mp3`

Does not work with `file://` prepended to the path either.

**Comment by dooboolab** [comment]
@janlonden Are you sure you can handle this `uri`. Does this actually exist in your device?

**Comment by dooboolab** [comment]
Closed for no response.
