### ISSUE TITLE
Playing audio from custom path passed in startPlayer(customPath)??

### ISSUE THREAD

**Issue by yash1511** [dooboolab/react-native-audio-recorder-player#149]
### Version of react-native-audio-recorder-player
v2.4.3
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behaviour
Play audio from provided file path in ```startPlayer(filePath)```
### Actual behaviour
Audio is not played as file path is not correct on logging it.
### Steps to reproduce the behaviour
Download an audio file from firebase storage in your app.
The file gets saved in a location such as this:  ``` file:///private/var/mobile/Containers/Data/Application/5374D364-778D-433E-B5F9-F0FA6720EBD2/Documents/Realyze/helloDownloaded.m4a```

Pass the above path in ```startPlayer()```, but it won't work because ```startPlayer()``` method tries to search for a file in ``` file:///private/var/mobile/Containers/Data/Application/5374D364-778D-433E-B5F9-F0FA6720EBD2/tmp/```

Hence on passing a different path; the path gets appended, like this:
```file:///private/var/mobile/Containers/Data/Application/5374D364-778D-433E-B5F9-F0FA6720EBD2/tmp/file:///private/var/mobile/Containers/Data/Application/5374D364-778D-433E-B5F9-F0FA6720EBD2/Documents/Realyze/helloDownloaded.m4a```

How can I play the file from the specified path that I pass??

**Comment by hyochan** [comment]
@yash1511 Thanks for coming up with this issue. I'll try to resolve this come back to you soon!

**Comment by yash1511** [comment]
Yeah, Thanks

**Comment by hyochan** [comment]
@yash1511 Could you try `2.4.4-rc.1`? I've made the fix in #151. I'll release to `2.4.4` when you are happy!

**Comment by hyochan** [comment]
@yash1511 How is it?

**Comment by milesscherrer** [comment]
I'm at 2.5.0 but this is still not working. 

The recording works and it is possible for me to record multiple audio files with different paths. 
However, when I call start player with the path of the second file, it still plays the first. It is very weird since when I do:
```
const msg = await this.audioRecorderPlayer.startPlayer(path);
console.log(msg)
```
with path being the path to the second file, console reads the second file's path but plays the first file.
