### ISSUE TITLE
Resume Record Functionality.

### ISSUE THREAD

**Issue by poojalodhi0704** [dooboolab/react-native-audio-recorder-player#15]
### Version of react-native-audio-recorder-player
2.0.8
### Platforms you faced the error (IOS or Android or both?)
Both
### Expected behavior
I am trying to pause the recorder and then resume it back again. I am not able to do that with the current set of APIs.
Is there a way to do this ?

Thanks in advance

**Comment by abdulrahman18** [comment]
@hyochan resumePlayer for using pause and play the recorded audio file. He asked for resumeRecord. I checked the index file not available for resume records

**Comment by anhtuank7c** [comment]
Yeah, pause recorder, not pause the player.

**Comment by hyochan** [comment]
It looks like a feature request! Thanks for posting.

**Comment by hyochan** [comment]
You can now use `3.0.+` for this functionality. However, note that the down side is you now require `minSdk` of `24` in Android.

**Comment by fisforfaheem** [comment]
brother still cant be able to use duplex moder why?
