### ISSUE TITLE
Loud short noise at the beginning of recorded audio

### ISSUE THREAD

**Issue by MariuszSpeednet** [dooboolab/react-native-audio-recorder-player#153]
### Version of react-native-audio-recorder-player
2.4.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Clear sound, as on Android

### Actual behavior
Loud short noise at the beginning of recorded audio

### Steps to reprodue the behabior
Everything as in example but using it together with react-native-camera (in fact mounting audio after unmounting camera)

**Comment by wayne530** [comment]
Example of noise: https://www.dropbox.com/s/mn4qw0fyeezr8fb/1575970204688-55696.m4a?dl=0

**Comment by Ayush1011** [comment]
please share your code im in lot of trouble
