### ISSUE TITLE
Cannot play ".mp3" file from an URL 

### ISSUE THREAD

**Issue by vrodrigos** [dooboolab/react-native-audio-recorder-player#156]
### Version of react-native-audio-recorder-player
2.4.4-rc.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Reproduce ".mp3" file from URL
### Actual behavior
Does not reproduce nothing

**Comment by hyochan** [comment]
Can you provide the `url` or any other minimal reproduction we can look into?

**Comment by s4kh** [comment]
It seems it cannot play mp3 encoded file like from google text to speech. The error is `Error: Prepare failed.: status=0x1`

**Comment by specter-kr2** [comment]
> It seems it cannot play mp3 encoded file like from google text to speech. The error is `Error: Prepare failed.: status=0x1`
help me please, what should I do with that error?

**Comment by Aung-Myint-Thein** [comment]
I tried "http://res.cloudinary.com/jerrywebie/video/upload/v1583996600/jerrywebie/auhgolxcu42cs5akuuds.mp3" and the code is 

`const msg = await this.audioRecorderPlayer.startPlayer("http://res.cloudinary.com/jerrywebie/video/upload/v1583996600/jerrywebie/auhgolxcu42cs5akuuds.mp3");`

The error said: "Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Can't find variable: audioRecorderPlayer"

**Comment by DalbirKaur** [comment]
I have just tried this method and it worked.
const msg = await audioRecorderPlayer.startPlayer('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3');
      console.log(msg);
      audioRecorderPlayer.addPlayBackListener((e) => {
        if (e.current_position === e.duration) {
          console.log('finished');
          audioRecorderPlayer.stopPlayer();
        }
        this.setState({
          currentPositionSec: e.current_position,
          currentDurationSec: e.duration,
          playTime: audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
          duration: audioRecorderPlayer.mmssss(Math.floor(e.duration)),
        });
        return;
      });

**Comment by DalbirKaur** [comment]
I have just tried this method and it worked fine.
const msg = await audioRecorderPlayer.startPlayer('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3');
      console.log(msg);
      audioRecorderPlayer.addPlayBackListener((e) => {
        if (e.current_position === e.duration) {
          console.log('finished');
          audioRecorderPlayer.stopPlayer();
        }
        this.setState({
          currentPositionSec: e.current_position,
          currentDurationSec: e.duration,
          playTime: audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
          duration: audioRecorderPlayer.mmssss(Math.floor(e.duration)),
        });
        return;
      });

**Comment by SanjayKumar10** [comment]
@DalbirKaur can you please let me know how to set up this audio player, am using rn 0.60, I followed the installation method, it's now working.

**Comment by chrisngabp** [comment]
I'm having a similar issue I think. When I try to use await this.audioRecorderPlayer.startPlayer(audioUrl), the response never comes and some components get freeze. 

Here is my code:

`export default class AudioPlayer extends Component {
   
    constructor(props) {
      super(props);

      this.state = {
        playing: false
      }

      this.audioRecorderPlayer = new AudioRecorderPlayer();

      this.playPausePlayer = this.playPausePlayer.bind(this)
      this.stopPlayer = this.stopPlayer.bind(this)
    }

    playPausePlayer = async () => {
    const audioUrl = "https://www.varocks.com/wp-content/uploads/mp3/Sonic%20Reducer.mp3";

      if (this.audioRecorderPlayer._isPlaying) {
        console.log("WAS PLAYING");
        this.stopPlayer();
        this.setState({
          playing: false
        });
        return;
      }

      try {
        const msg = await this.audioRecorderPlayer.startPlayer(audioUrl);
        console.log(msg);
        this.setState({
          playing: !this.state.playing
        });
      } catch(e) {
        console.log(e);
      }
    }

    stopPlayer = async () => {
      this.audioRecorderPlayer.stopPlayer();
      this.audioRecorderPlayer.removePlayBackListener();
    }

    render() {
        const IconComponent = Icons;
        var iconName = this.state.playing ? 'controller-stop' : 'controller-play';

        return (
        <View style={styles.container}>
          <View style={styles.innerContainer}>
            <Text onPress={this.playPausePlayer}>
              <IconComponent style={styles.playPauseButton} name={iconName} size={40} />
            </Text>
          </View>
        </View>
        );
    }
}`

And here is my package.json:

`{
  "name": "Sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest --detectOpenHandles",
    "prettier-fix": "prettier --write **/*.js",
    "prettier-check": "prettier --list-different **/*.js",
    "lint-fix": "eslint --fix .",
    "lint-check": "eslint .",
    "rename": "react-native-rename",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-audio-recorder-player": "^2.5.1",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-permissions": "^2.1.4",
    "react-native-reanimated": "^1.7.1",
    "react-native-screens": "^2.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.2",
    "react-navigation-stack": "^2.3.11",
    "react-navigation-tabs": "^2.8.11",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.2",
    "reduxsauce": "^1.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^4.1.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-node": "^8.0.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "eslint-plugin-standard": "^4.0.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "prettier": "^1.16.4",
    "react-native-rename": "^2.4.1",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!react-native)/.+"
    ]
  }
}
`

**Comment by Aung-Myint-Thein** [comment]
Is there a good example on how to play audio file from local JS / Android / iOS folder? For example, I want to include small mp3 files in the apk and play them. Since they are small, I don't need to download them. 🙂

**Comment by Harikasai999** [comment]
How can i add slider or seekBar for this audio player???
I will play .mp3 file from URL. But how can i add the seekBar or slider for this audio file.
Please give any suggestions.

**Comment by daimonkor** [comment]
> I'm having a similar issue I think. When I try to use await this.audioRecorderPlayer.startPlayer(audioUrl), the response never comes and some components get freeze.
> 
> **EDIT:** I've been investigating a bit more. The problem I'm having is that MediaPlayer returns Prepare failed.: status=0x1. **EDIT 2:** I've also tried in an iOS simulator, and it works fine. It seems to be the Android Simulator, surely a problem with SSL certificates trust. **EDIT 3:** Confirmed, running on a real android device works too.
> 
> Here is my code:
> 
> ` export default class AudioPlayer extends Component {
> 
> ```
> constructor(props) {
>   super(props);
> 
>   this.state = {
>     playing: false
>   }
> 
>   this.audioRecorderPlayer = new AudioRecorderPlayer();
> 
>   this.playPausePlayer = this.playPausePlayer.bind(this)
>   this.stopPlayer = this.stopPlayer.bind(this)
> }
> 
> playPausePlayer = async () => {
> const audioUrl = "https://www.varocks.com/wp-content/uploads/mp3/Sonic%20Reducer.mp3";
> 
>   if (this.audioRecorderPlayer._isPlaying) {
>     console.log("WAS PLAYING");
>     this.stopPlayer();
>     this.setState({
>       playing: false
>     });
>     return;
>   }
> 
>   try {
>     const msg = await this.audioRecorderPlayer.startPlayer(audioUrl);
>     console.log(msg);
>     this.setState({
>       playing: !this.state.playing
>     });
>   } catch(e) {
>     console.log(e);
>   }
> }
> 
> stopPlayer = async () => {
>   this.audioRecorderPlayer.stopPlayer();
>   this.audioRecorderPlayer.removePlayBackListener();
> }
> 
> render() {
>     const IconComponent = Icons;
>     var iconName = this.state.playing ? 'controller-stop' : 'controller-play';
> 
>     return (
>     <View style={styles.container}>
>       <View style={styles.innerContainer}>
>         <Text onPress={this.playPausePlayer}>
>           <IconComponent style={styles.playPauseButton} name={iconName} size={40} />
>         </Text>
>       </View>
>     </View>
>     );
> }
> ```
> 
> } `
> 
> And here is my package.json:
> 
> `{ "name": "Sample", "version": "0.0.1", "private": true, "scripts": { "android": "react-native run-android", "ios": "react-native run-ios", "start": "react-native start", "test": "jest --detectOpenHandles", "prettier-fix": "prettier --write **/*.js", "prettier-check": "prettier --list-different **/*.js", "lint-fix": "eslint --fix .", "lint-check": "eslint .", "rename": "react-native-rename", "postinstall": "npx jetify" }, "dependencies": { "axios": "^0.19.0", "prop-types": "^15.7.2", "react": "16.9.0", "react-native": "0.61.5", "react-native-audio-recorder-player": "^2.5.1", "react-native-gesture-handler": "^1.3.0", "react-native-permissions": "^2.1.4", "react-native-reanimated": "^1.7.1", "react-native-screens": "^2.4.0", "react-native-vector-icons": "^6.6.0", "react-navigation": "^3.11.2", "react-navigation-stack": "^2.3.11", "react-navigation-tabs": "^2.8.11", "react-redux": "^6.0.1", "redux": "^4.0.1", "redux-persist": "^5.10.0", "redux-saga": "^1.0.2", "reduxsauce": "^1.0.1" }, "devDependencies": { "@babel/core": "^7.6.2", "@babel/runtime": "^7.6.2", "@react-native-community/eslint-config": "^0.0.5", "babel-jest": "^24.9.0", "eslint": "^6.5.1", "eslint-config-prettier": "^4.1.0", "eslint-config-standard": "^12.0.0", "eslint-plugin-import": "^2.16.0", "eslint-plugin-node": "^8.0.1", "eslint-plugin-prettier": "^3.0.1", "eslint-plugin-promise": "^4.0.1", "eslint-plugin-react": "^7.12.4", "eslint-plugin-react-native": "^3.6.0", "eslint-plugin-standard": "^4.0.0", "jest": "^24.9.0", "metro-react-native-babel-preset": "^0.56.0", "prettier": "^1.16.4", "react-native-rename": "^2.4.1", "react-test-renderer": "16.9.0" }, "jest": { "preset": "react-native", "setupFiles": [ "./node_modules/react-native-gesture-handler/jestSetup.js" ], "transformIgnorePatterns": [ "/node_modules/(?!react-native)/.+" ] } }`

The same bug. If url is 404, freezed components
