### ISSUE TITLE
Can not start recording, getting warning of setSubscriptionDuration.

### ISSUE THREAD

**Issue by Harsh2402** [dooboolab/react-native-audio-recorder-player#16]
### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^2.0.8",
"react": "^16.5.1",
"react-native": "0.57.0",

### Platforms you faced the error (IOS or Android or both?)
- Android

Getting following types of warning and can not start record an audio, I have given run-time permissions for the record an audio too..

![device-2018-10-02-172949](https://user-images.githubusercontent.com/20766131/46347428-16221c00-c669-11e8-9e74-9d97747603ef.png)

I have shared my code too.

import React, {Component} from 'react';
import {
    StyleSheet,
    Text, Button,
    PermissionsAndroid,
    View, TouchableOpacity, StatusBar
} from 'react-native';
import AudioRecorderPlayer from 'react-native-audio-recorder-player';

export default class AudioRecord extends React.Component<> {

    audioRecorderPlayer: AudioRecorderPlayer;

    constructor(props) {
        super(props);
        this.state = {
            emailText: "",
            password: ""
        };
        this.audioRecorderPlayer = new AudioRecorderPlayer();
        this.audioRecorderPlayer.setSubscriptionDuration(0.09); // optional. Default is 0.1
    }

    onStartRecord = async () => {
        const result = await this.audioRecorderPlayer.startRecorder();
        this.audioRecorderPlayer.addRecordBackListener((e) => {
            this.setState({
                recordSecs: e.current_position,
                recordTime: this.audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
            });
        });
    };

    onStopRecord = async () => {
        const result = await this.audioRecorderPlayer.stopRecorder();
        this.audioRecorderPlayer.removeRecordBackListener();
        this.setState({
            recordSecs: 0,
        });
    };

    onStartPlay = async () => {
        const msg = await this.audioRecorderPlayer.startPlayer();
        this.audioRecorderPlayer.addPlayBackListener((e) => {
            if (e.current_position === e.duration) {
                this.audioRecorderPlayer.stopPlayer();
            }
            this.setState({
                currentPositionSec: e.current_position,
                currentDurationSec: e.duration,
                playTime: this.audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
                duration: this.audioRecorderPlayer.mmssss(Math.floor(e.duration)),
            });
            return;
        });
    };

    onPausePlay = async () => {
        await this.audioRecorderPlayer.pausePlayer();
    };

    onStopPlay = async () => {
        this.audioRecorderPlayer.stopPlayer();
        this.audioRecorderPlayer.removePlayBackListener();
    };

    render() {
        return (
            <View style={styles.imageStyle} >
                <StatusBar
                    backgroundColor='#BCE1FE'
                    barStyle="light-content"
                />

                <View style={{flex:1,flexDirection:'row'}}>
                    <TouchableOpacity
                        activeOpacity = { .5 }
                        onPress={() => this.onStartRecord()}>
                        <Text style={[styles.signup,{color:'black',fontSize:16}]}>onStartRecord</Text>
                    </TouchableOpacity>
                </View>

                <View style={{flex:1,flexDirection:'row'}}>
                    <TouchableOpacity
                        activeOpacity = { .5 }
                        onPress={() => this.onStopRecord()}>
                        <Text style={[styles.signup,{color:'black',fontSize:16}]}>onStopRecord</Text>
                    </TouchableOpacity>
                </View>

                <View style={{flex:1,flexDirection:'row', marginTop:10}}>
                    <TouchableOpacity
                        activeOpacity = { .5 }
                        onPress={() => this.onStartPlay()}>
                        <Text style={[styles.signup,{color:'black',fontSize:16}]}>onStartPlay</Text>
                    </TouchableOpacity>
                </View>

            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#0ED2F7',
    },
    imageStyle: {
        flex: 1, backgroundColor: '#0ED2F7', alignItems: 'center'
    },
    inputBox: {
        width: 300,
        borderRadius: 25,
        borderColor:'#19295c',
        borderWidth: 2,
        paddingHorizontal: 16,
        fontSize: 16,
        color: '#19295c',
        marginVertical: 10
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        color: '#333333',
        margin: 20,
    },
    signup: {
        fontSize: 15,
        textAlign: 'center',
        color: '#333333',
        marginTop:50,
        marginLeft:5
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
    },
    button: {
        width: 300,
        backgroundColor: '#19295c',
        borderRadius: 25,
        marginVertical: 10,
        paddingVertical: 13
    },
    buttonText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#ffffff',
        textAlign: 'center'
    }
});

**Comment by dooboolab** [comment]
@Harsh2402 Could you try our example project and comeback?

**Comment by Harsh2402** [comment]
@dooboolab 
I have cloned this project but facing following error, so I have applied the same in demo. 
Can u pls help me to solve this for this demo and anything wrong in my above code which I have applied in seperate demo.

![device-2018-10-03-161903](https://user-images.githubusercontent.com/20766131/46406161-3fee4800-c728-11e8-8284-56d4de6a841d.png)
