### ISSUE TITLE
Playback listener not emitting events with duration & position for IOS when player is paused

### ISSUE THREAD

**Issue by vinithreddy3** [dooboolab/react-native-audio-recorder-player#165]
Version of react-native-audio-recorder-player  -- 2.4.4-rc.1

Platforms you faced the error  - IOS

Expected behavior - Playback listener should emit events which provide current position and current duration  when the player is available or a seek to is performed

Actual behavior - Playback listener not emitting events with the current position / current duration when the player is in the paused state

Perform seek to when the player is paused, playback listener doesn't emit events in ios in contrary to android which does.

**Comment by hyochan** [comment]
Looks like the doc is wrong. You should pass `miliseconds`.
