### ISSUE TITLE
Warning Error: mediaPlayer is null when called stopPlayer funtion

### ISSUE THREAD

**Issue by rodrigowpl** [dooboolab/react-native-audio-recorder-player#17]
### Version of react-native-audio-recorder-player
2.0.8

### Platforms you faced the error (IOS or Android or both?)
Android 8.0.0

### Expected behavior
When calls the stopPlayer() function, It's work fine, but show a warning that is annexed below

### Actual behavior
Don't show warning when call stopPlayer function

### Steps to reprodue the behabior
call stopPlayer()

Here is my code:

startPlay function
```
 this.recorderPlayer.addPlayBackListener(e => {
    if (e.current_position === e.duration) {
        this.stopPlay()
        return
    }
    return
  })
```

stopPlay funtion
```
stopPlay = () => {
    this.recorderPlayer.stopPlayer()
    this.recorderPlayer.removePlayBackListener()
}
```

[
![war](https://user-images.githubusercontent.com/18172307/46636738-9e079a80-cb2f-11e8-9f24-3bc8ba245ae4.jpeg)
](url)

**Comment by dooboolab** [comment]
@RodrigoWP Thank you for the `PR`. Would you mind giving a `PR` to resolve this one? Because it may take some time for me to resolve this because I am quite having a hard time maintaining my other repositories.

**Comment by thefallenangel** [comment]
I get same error at version 2.0.9

**Comment by dooboolab** [comment]
Actually, you can ignore this warning message because it is to inform you where your code might not be `thread safe`. If you try to stopPlayer twice, and once it is already stopped, that message will appear. Also if you tried to start the player when it is stopped and released already, that warning message will appear too.

**Comment by OlStoppa** [comment]
You could throw a catch onto the stopPlayer method.
`this.recorderPlayer.stopPlayer.catch(()=>{});`

**Comment by chandanrai95** [comment]
is it solve the problem

**Comment by abhishektiwari-kiwi** [comment]
Any update on this?

**Comment by JeanEXE** [comment]
same problem.

**Comment by primeloop** [comment]
this.audioRecorderPlayer.stopPlayer().catch(()=>{}); @OlStoppa

**Comment by hyochan** [comment]
v3 is out everyone!
