### ISSUE TITLE
Handling Interrupts During Recording

### ISSUE THREAD

**Issue by dbirchfield80** [dooboolab/react-native-audio-recorder-player#170]
### Version of react-native-audio-recorder-player
2.4.4-rc.1
### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
When recording an audio file, an interrupt event occurs. For example, a countdown timer expires in the iOS Timer app, generating an alarm. Or, a phone call comes in and is left unanswered. https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/HandlingAudioInterruptions/HandlingAudioInterruptions.html

Is it possible to handle this type of interrupt? Ideally, triggering a Pause recording action when the interrupt occurs, then a Resume recording once the interrupt is completed.

### Actual behavior
The interrupt occurs, and recording stops and does not resume.

### Steps to reprodue the behabior
Start a recording, trigger an Alarm by setting a short countdown timer in the iOS Timer app.

**Comment by hyochan** [comment]
Looks like this is another feature request. Currently, we don't take care of that situation and you should have to re-record them.

**Comment by hyochan** [comment]
Related # 15

**Comment by joshmohrer** [comment]
does anyone know if this ever got fixed in the subsequent 3 years? I recall this working for me properly a few months ago - a phone call or alarm would pause the recording - but now it seems to just scrap it.

**Comment by pipi32167** [comment]
Look at [this](https://github.com/hyochan/react-native-audio-recorder-player/pull/600)

**Comment by joshmohrer** [comment]
This is fantastic - thank you @pipi32167 @hyochan Works great!
