### ISSUE TITLE
DEMO - Example start error（IOS）

### ISSUE THREAD

**Issue by renyi818** [dooboolab/react-native-audio-recorder-player#179]
### Version of react-native-audio-recorder-player
latest version 
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Launch DEMO
### Actual behavior
ERROR：
`error: bundling failed: Error: While trying to resolve module `react-native-audio-recorder-player` from file `/react-native-audio-recorder-player/Example/src/components/screen/Intro.tsx`, the package `/react-native-audio-recorder-player/Example/node_modules/react-native-audio-recorder-player/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/react-native-audio-recorder-player/Example/node_modules/react-native-audio-recorder-player/index.js`. Indeed, none of these files exist:`

### Steps to reprodue the behabior
1.yarn
2.cd ios && pod install
3.return example
   react-native  run-ios

**Comment by hyochan** [comment]
Can you try to install latest `react-native-audio-recorder-player` in `example` and try again? @renyi818 renyi818

**Comment by renyi818** [comment]
Yes, I failed again...

**Comment by renyi818** [comment]
I found the solution，Thank you！

**Comment by usamaabutt** [comment]
@renyi818 what's the solution which have found ?

**Comment by hyochan** [comment]
@usamaabutt Would you try to build the module then start the `Example`?

In root,
```
yarn && yarn build
```

Then go to `Example`
```
cd Example && yarn && yarn start
```
