### ISSUE TITLE
Unable to resolve module `react-native-audio-recorder-player` from `src\components\screen\Intro.tsx`: react-native-audio-recorder-player

### ISSUE THREAD

**Issue by nicolasscard** [dooboolab/react-native-audio-recorder-player#180]
### Version of react-native-audio-recorder-player
2.3.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
run without error

### Actual behavior
bundling failed: Error: Unable to resolve module `react-native-audio-recorder-player` from `src\components\screen\Intro.tsx`: react-native-audio-recorder-player could not be found within the project

### Steps to reprodue the behabior
go to example directory
npm install
react-native run-android (in physical device)

##Description
How is it possible that the library itself cannot include itself?
I tried reinstalling it with
npm i react-native-audio-recorder-player
but it was not enough

**Comment by matthewadel** [comment]
did you tried 
react-native-audio-recorder-player

**Comment by hyochan** [comment]
@nicolasscard Could you specify react-native version? Looks like `react-native` can't find the native modules which means it looks like a linking problem.

**Comment by hyochan** [comment]
Hope you to follow the [link](https://github.com/dooboolab/react-native-audio-recorder-player/issues/181#issuecomment-603757413) also.
