### ISSUE TITLE
Properly reset recorder

### ISSUE THREAD

**Issue by sofianegargouri** [dooboolab/react-native-audio-recorder-player#188]
One of the features should be to reset the recorder to restart the current recording.

The only way I found to achieve this is the following, but it doesn't seem to be stable.

```
  const reset = () => {
    recorderRef.current = new AudioRecorderPlayer();
    unlink(fileUrl); // unlink from react-native-fs
  };
```

I sometimes get the following errors: 
1. `no such file or directory, open 'Already stopped'`
2. Sometimes a new record stops when reaching the previous record's length

**Comment by hyochan** [comment]
@sofianegargouri For no.1, I made this to print the warning console when you try to stop the recorder when the recorder has already stopped!

I've not have experienced `no.2`. I need to know why this happens.

Try to stop the recorder and start again when you are doing new recording~!
