### ISSUE TITLE
Background playing not working

### ISSUE THREAD

**Issue by nahog** [dooboolab/react-native-audio-recorder-player#19]
### Version of react-native-audio-recorder-player
2.0.8
### Platforms you faced the error (IOS or Android or both?)
both
### Expected behavior
Sound keeps playing in the background
### Actual behavior
Sound stops if the app loses focus
### Steps to reproduce the behavior
Run the example application, hit the play button, while playing hit the home button.

In the attached medium post, it says that the library supports background music playing, but when the app is in the background the sound stops, I looked in the code to see if there is some extra parameter I need to pass to addPlayBackListener but I cannot find anything.

I'm I missing something?

**Comment by dooboolab** [comment]
@nahog I should work if you configure remote notification.

**Comment by abhishektiwari-kiwi** [comment]
@hyochan Hi, Could you please tell me how exactly we can achieve this background playing functionality.
