### ISSUE TITLE
Recording/playback stops when phone gets locked

### ISSUE THREAD

**Issue by andystewart12** [dooboolab/react-native-audio-recorder-player#193]
### Version of react-native-audio-recorder-player
2.5.0

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
When recording or playing back a recording, it should continue when the phone goes into locked mode. If a user has auto-lock set on their phone to 1 or 2 minutes then the phone is likely to lock before a recording is finished.

### Actual behavior
Recording stops and playback stops. This is more critical for recording since a user would have to start again if it gets cut short.

### Steps to reproduce the behavior
Start a recording or playback and let the phone auto-lock.

**Comment by hyochan** [comment]
Looks like this is another feature request to handle with the track player.

**Comment by abhishektiwari-kiwi** [comment]
Any update on this ?
