### ISSUE TITLE
Ability to delete recordings

### ISSUE THREAD

**Issue by andystewart12** [dooboolab/react-native-audio-recorder-player#195]
This is also addressed in https://github.com/dooboolab/react-native-audio-recorder-player/issues/29.

I am making an app where users are encouraged to keep more than one recording, so overwriting with the same path is not a viable solution.

Would it be possible to add the ability to delete the recording at a specific path?

**Comment by Daniyal857** [comment]
I was also looking for this feature, to delete the recorded audio.
Also, would it be possible to limit the user audio recording for a defined no. of minute?

**Comment by faizantariq1** [comment]
@andystewart12  did you find the solution of delete recording?

**Comment by LWilsonDev** [comment]
You can delete the files using RNFS. I found this post helpful https://stackoverflow.com/questions/41352198/react-native-file-handling-delete-image 
I passed the audio file path and it worked for me:


```import RNFS from 'react-native-fs';

const deleteAudioFile = (path: string) => {
  RNFS.exists(path)
    .then(result => {
      if (result) {
        return (
          RNFS.unlink(path)
            .then(() => {
              /console.log('FILE DELETED');
            })
            // `unlink` will throw an error, if the item to unlink does not exist
            .catch(err => {
              console.log(err.message);
            })
        );
      }
    })
    .catch(err => {
      console.log(err.message);
    });
};
```
