### ISSUE TITLE
seekToPlayer not working

### ISSUE THREAD

**Issue by preduseldavid** [dooboolab/react-native-audio-recorder-player#197]
seekToPlayer has different behaviour in android and iOS: for android it is working with seconds and the documentation says that the param should be miliseconds.

this is the code:

```
this.audioRecorderPlayer.seekToPlayer(
    Platform.OS == 'ios' ? msecs : msecs / 1000,
);
```

**Comment by hyochan** [comment]
Could you specify the version and checkout the `example` project?

**Comment by Evanfeenstra** [comment]
i notice this too, android works if you use seconds (not milliseconds). Im using 2.5.0

**Comment by Jongkeun** [comment]
@hyochan 
It still doesn't work.
I'm using 2.6.0-rc3.
Any updates?

**Comment by durdevic** [comment]
So I don't know if this is connected with this issue, but whenever I use scrubber to jump forward on the audio on Android, it automatically jumps to the end and stops the audio.

I tested with the Example as well, and I get the same result. 

On iOS it works fine.
