### ISSUE TITLE
Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by shaheem-khanzada** [dooboolab/react-native-audio-recorder-player#2]
![image](https://user-images.githubusercontent.com/37620819/42733887-6a7b9e1a-8853-11e8-9146-d8420c647c39.png)

**Comment by dooboolab** [comment]
<img width="330" alt="screen shot 2018-07-17 at 2 03 39 pm" src="https://user-images.githubusercontent.com/27461460/42797439-3821347a-89ca-11e8-8d24-bee022467ffc.png">
Do you have ext setup in build.gradle?
This should be default in recent react-native project.

What version are you on?
