### ISSUE TITLE
Player not working Smoothly and hangs the screen

### ISSUE THREAD

**Issue by babitakapoor112** [dooboolab/react-native-audio-recorder-player#208]
Hey there
### Version of react-native-audio-recorder-player
2.5.0
### Platforms you faced the error (IOS or Android or both?)
android and ios both
### Expected behavior
an audio player should work smoothly.
### Actual behavior
When  I click on the react-native-slider to pause it or I click on the button to pause it hangs the screen and I am not able to close it. While playing it does not want me to do anything.
steps to reprodudce 
code used in the render() method 
<View style={{flex:1,flexDirection:'row',bottom:hp('8%'),marginLeft:wp('5%'),marginRight:wp('60%')}}>
                                {(this.playerStatus=='playing') ?
                                <TouchableOpacity onPress={()=>{
                                if(this.playerStatus == "playing"){
                                    this.playerStatus = "paused";
                                    this.onPausePlay();
                                }
                                else{
                                    this.onStopPlay()
                                }
                                }}>
                                <Icon name="pause" type={'font-awesome'} size={20} color={'#fff'}/>
                                </TouchableOpacity>
                                :<TouchableOpacity onPress={()=>{this.onStartPlay()}}><Icon size={25} name="play" type={'font-awesome'} color={'#fff'}/></TouchableOpacity>
                                }
                            </View>
                            <View style={{flex:1,flexDirection:'row',bottom:hp('13.8%')}}>
                                <Slider
                                style={{width: wp('100%'), height: 60}}
                                value={this.state.currentPositionSec}
                                minimumValue={0}
                                maximumValue={this.state.currentDurationSec}
                                onValueChange={(data) => {
                                console.log(this.playerStatus);
                                if(this.playerStatus == "playing"){
                                    this.setState({isLoading:true});
                                    console.log("in value change onPause play");
                                    this.playerStatus = "paused";
                                    this.onPausePlay();
                                }

                              }}
                              onSlidingComplete={async (data) => 

{
                                console.log(data);
                                console.log("set");
                                await audioRecorderPlayer.seekToPlayer(data/1000);
                                this.onStartPlay();
                                this.setState({isLoading:false});
                                }}
                                thumbTintColor={'transparent'}
                                minimumTrackTintColor="#39B2DB"
                                maximumTrackTintColor="#FFFFFF"
                                />
                            </View>

Functions used for audio play

 onStartPlay = async () => {
        this.playerStatus = "playing";
        const msg = await audioRecorderPlayer.startPlayer(this.state.audioPath);
     //   const msg = await audioRecorderPlayer.startPlayer('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3');
        audioRecorderPlayer.setVolume(1.0);
        if(this.seekPosition && this.playerStatus == "paused"){
            audioRecorderPlayer.seekToPlayer(this.seekPosition);
        }
        audioRecorderPlayer.addPlayBackListener((e) => {
        this.seekPosition = e.current_position;
          if (e.current_position === e.duration) {
          this.setState({isLoading:false});
          this.playerStatus = "stopped";
          audioRecorderPlayer.stopPlayer();
          }
          this.setState({
            currentPositionSec: e.current_position,
            currentDurationSec: e.duration,
            playTime: audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
            duration: audioRecorderPlayer.mmssss(Math.floor(e.duration)),
          });
          return;
        });
      }

      async onPausePlay(){ 
      this.playerStatus = "paused";
        await audioRecorderPlayer.pausePlayer();
      }
     async onStopPlay(){
        console.log('onStopPlay');
        this.playerStatus = "stopped";
        audioRecorderPlayer.stopPlayer();
        audioRecorderPlayer.removePlayBackListener();
      };

**Comment by abhishektiwari-kiwi** [comment]
Any update on this?
Is it because of the listener is way too frequent?
Please help...

**Comment by iamabdulhaseeb** [comment]
Did any one solve this issue

**Comment by bhargav-trt** [comment]
Did any one solve this issue? i am having same problem
