### ISSUE TITLE
Help Needed.

### ISSUE THREAD

**Issue by priyankverma** [dooboolab/react-native-audio-recorder-player#21]
Hello, 
Thanks for such a stable and useful plugin.
I need to have a callback when an audio from network gets loaded and is ready to be played.
Please suggest how it can be done.

**Comment by dooboolab** [comment]
I guess the native `mediaPlayer` will handle this automatically so to achieve this, I think the only way to do is by downloading the audio file to local storage then play it. [Read](https://stackoverflow.com/questions/13863724/android-media-player-download-to-file-and-stream-from-file) here too.
