### ISSUE TITLE
How i can add .aac output format for Android?

### ISSUE THREAD

**Issue by meDev-lab** [dooboolab/react-native-audio-recorder-player#211]
### Platforms you faced the error (IOS or Android or both?)  - Android

```js
const onRec = async () => {
    if(!isRecordVoice){
      await audioRecorderPlayer.startRecorder(_,{AudioEncoderAndroid: AudioEncoderAndroidType.AAC})
    } else {
      await audioRecorderPlayer.stopRecorder()
    }
  }
```

I tried with ``` {AudioEncoderAndroid: AudioEncoderAndroidType.AAC} ``` but it not work

**Comment by southpaw2729** [comment]
Just pass it as a parameter. For eg.

const result = await audioRecorderPlayer.startRecorder('sdcard/sound.aac');

**Comment by deepakgd** [comment]
@southpaw2729 i tried this but  content type is showing as video/mp4

**Comment by marcosPerezRubio** [comment]
Hey! I've got this issue also. 

Looking at the definition in index.d.ts, it looks like there ara three parameters that have to be specified:

    startRecorder: (uri?: string, meteringEnabled?: boolean, audioSets?: AudioSet) => Promise<string>;

Using the recorder with the following, it works:

audioRecorderPlayer.startRecorder(filepath, true, {AVFormatIDKeyIOS: AVEncondingOption.aac})

Hope this helps!

**Comment by hyochan** [comment]
Please check our [example code](https://github.com/dooboolab/react-native-audio-recorder-player/blob/a3f4fa5e62fd35b900bc3c03d13e870d6f9ea56b/Example/src/components/screen/Intro.tsx#L277-L298). I think this will be enough for current issue!

**Comment by beqramo** [comment]
meteringEnabled to true worked for me

**Comment by Fischaela** [comment]
> @southpaw2729 i tried this but content type is showing as video/mp4

I am having the same issue – wether meteringEnabled is true or not. I always get a video/ mime type no matter which codec I choose. Can anyone help me?

**Comment by Bsingh2697** [comment]
> > @southpaw2729 i tried this but content type is showing as video/mp4
> 
> I am having the same issue – wether meteringEnabled is true or not. I always get a video/ mime type no matter which codec I choose. Can anyone help me?

SAME issue

**Comment by Bsingh2697** [comment]
> Hey! I've got this issue also.
> 
> Looking at the definition in index.d.ts, it looks like there ara three parameters that have to be specified:
> 
> ```
> startRecorder: (uri?: string, meteringEnabled?: boolean, audioSets?: AudioSet) => Promise<string>;
> ```
> 
> Using the recorder with the following, it works:
> 
> audioRecorderPlayer.startRecorder(filepath, true, {AVFormatIDKeyIOS: AVEncondingOption.aac})
> 
> Hope this helps!

The order is wrong!
