### ISSUE TITLE
stopPlayer() not workin 

### ISSUE THREAD

**Issue by maxckelly** [dooboolab/react-native-audio-recorder-player#215]
### Version of react-native-audio-recorder-player
`react-native-audio-recorder-player": "^2.5.2`

### Platforms you faced the error (IOS or Android or both?)
iOS - simulator

### Expected behavior
Stop audio

### Actual behavior
Audio keeps playing

### Steps to reproduce the behavior
1. Signup
2. Press microphone icon
2. click next till you get to recording screen
3. Press listen to question button
4. Press Stop question -- Question won't stop

Hi,

I'm trying to stop the audio which I'm playing from a URL linked to my s3 bucket. Playing the audio works fine but when I go to stop it for some reason it doesn't work. See below code. Any help would be appreciated.

I've double checked if everything was referencing and if the `pauseAudio` function was being called, which all was. 

- Parent Component: `StoryRecordingScreen`
```
 const audioRecorderPlayer = new AudioRecorderPlayer();
 
  // Pause Audio
  const pauseAudio = async () => {
    audioRecorderPlayer.stopPlayer();
    audioRecorderPlayer.removePlayBackListener();
    return setRecordingStatus("IDLE");
  };

        <StoryQuestionSectionComponent 
          questionTitle={questions ? questions[questionIndex].title : null}
          questionAudioURL={questions ? questions[questionIndex].audioFileURL : null}
          questionID={questions ? questions[questionIndex].id : null}
          isAudioPlaying={recordingStatus}
          playAudio={(audioFile) => playAudio(audioFile)}
          pauseAudio={() => pauseAudio()}
          questionAudioPlaying={(isAudioPlaying) => setRecordingStatus(isAudioPlaying)}
          capturedAudio={recordedAudioFile}
        />
```

Child Component

```
        return (
          <TouchableOpacity onPress={() => pauseAudio()} style={styles.touchableOpacityContainer}>
            <MaterialCommunityIcons
              name="stop-circle"
              size={ICON_SIZE.iconSizeLarge}
              color={COLOR.white}
            />
            <Text> Stop question </Text>
          </TouchableOpacity>
        );
```

**Comment by hyochan** [comment]
Hopefully, this would fix in `2.5.3` related to #220. Feel free to reopen if there is still a problem.
