### ISSUE TITLE
Recorded AAC from ios cannot play on Android

### ISSUE THREAD

**Issue by Moonubanna** [dooboolab/react-native-audio-recorder-player#221]

**Comment by marcosPerezRubio** [comment]
Hey! Just faced this today, and maybe it's the same issue.

By default, on IOS the audio files are encoded with ALAC (which is not related to AAC), and thus recordings are only playable from other apple products like safari or quicktime.

You can change the default ios encoding format, specifying the AVEncondingOption.aac.

Hope this helps!

**Comment by hyochan** [comment]
Looks like it is related to #211. Would this help?
