### ISSUE TITLE
Cannot record or play

### ISSUE THREAD

**Issue by sdakansu** [dooboolab/react-native-audio-recorder-player#223]
### Version of react-native-audio-recorder-player
2.5.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Record and play sound.

### Actual behavior
Record and play methods does not working. I encounter promise rejection warnings. 

>  audioSet {"AVEncoderAudioQualityKeyIOS": 96, "AVFormatIDKeyIOS": "aac", "AVNumberOfChannelsKeyIOS": 2, "AudioEncoderAndroid": 3, "AudioSourceAndroid": 1}
> [Thu Aug 27 2020 23:33:10.295]  WARN     Possible Unhandled Promise Rejection (id: 5):
> TypeError: undefined is not an object (evaluating '_this.audioRecorderPlayer.startRecorder')
> onStartRecord$@http://localhost:8081/App.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:145:72
> tryCatch@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
> invoke@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28816:32
> tryCatch@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
> invoke@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28716:30
> http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28746:19
> tryCallTwo@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:3484:9
> doResolve@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:3648:25
> Promise@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:3507:14
> callInvokeWithMethodAndArg@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28745:33
> enqueue@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28750:157
> http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:28767:69
> onStartRecord@http://localhost:8081/App.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:48:38
> onPress@http://localhost:8081/App.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:284:29
> _performTransitionSideEffects@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:55107:22
> _receiveSignal@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:55049:45
> onResponderRelease@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:54958:34
> invokeGuardedCallbackImpl@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:12853:21
> invokeGuardedCallback@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:12947:42
> invokeGuardedCallbackAndCatchFirstError@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:12951:36
> executeDispatch@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:13023:48
> executeDispatchesInOrder@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:13043:26
> executeDispatchesAndRelease@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14118:35
> forEach@[native code]
> forEachAccumulated@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:13185:22
> runEventsInBatch@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14142:27
> runExtractedPluginEventsInBatch@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14221:25
> http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14197:42
> batchedUpdates$1@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:24846:20
> batchedUpdates@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14104:36
> _receiveRootNodeIDEvent@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14196:23
> receiveTouches@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:14249:34
> __callFunction@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:2798:36
> http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:2530:31
> __guard@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:2752:15
> callFunctionReturnFlushedQueue@http://192.168.2.139:8081/index.bundle?platform=ios&dev=true&minify=false:2529:21
> callFunctionReturnFlushedQueue@[native code]

### Steps to reproduce the behavior

```
export default function App() {

 const audioRecorderPlayer = new AudioRecorderPlayer();

onStartRecord = async () => {
  
  const result = await this.audioRecorderPlayer.startRecorder( "/Users/selamidoganakansu/Desktop" ,true);
  this.audioRecorderPlayer.addRecordBackListener((e) => {
    this.setState({
      recordSecs: e.current_position,
      recordTime: this.audioRecorderPlayer.mmssss(
        Math.floor(e.current_position),
      ),
    });
    return;
  });
  console.log(result);
};


onStopRecord = async () => {
  const result = await audioRecorderPlayer.stopRecorder();
  audioRecorderPlayer.removeRecordBackListener();
  React.setState({
    recordSecs: 0,
  });
  console.log(result);
};

async function onStartPlay(path, callback) {
  //console.log({ currentPath, path })

  if (currentPath === undefined) {
    currentPath = path
    currentCallback = callback
  } else if (currentPath !== path) {
    if (audioRecorderPlayer !== undefined) {
      try {
        await stopPlayer()
      } catch (error) {
        console.log('ERROR STOP PLAYER TOP')
      }
    }
    currentPath = path
    currentCallback = callback
  }

  if (audioRecorderPlayer === undefined) {
    audioRecorderPlayer = new AudioRecorderPlayer()
  }

  try {
    const activePath = await audioRecorderPlayer.startPlayer(currentPath);
    console.log({ activePath })
    currentCallback({
      status: (currentPath === path) && (currentPosition > 0) ? AUDIO_STATUS.resume : AUDIO_STATUS.begin
    })
    audioRecorderPlayer.addPlayBackListener(async (e) => {
      if (e.current_position === e.duration) {
        try {
          await stopPlayer()
        } catch (error) {
          console.log('ERROR STOP PLAYER IN LISTENER')
        }
      } else {
        currentPosition = e.current_position
        currentCallback({
          status: AUDIO_STATUS.play,
          data: e
        })
      }
      return
    });
  } catch (error) {
    console.log({ 'ERROR PLAY PLAYER': error })
  }
}

onPausePlay = async () => {
  await audioRecorderPlayer.pausePlayer();
};

onStopPlay = async () => {
  console.log('onStopPlay');
  audioRecorderPlayer.stopPlayer();
  audioRecorderPlayer.removePlayBackListener();
};




  return(
  <SafeAreaView>
    <TouchableOpacity  onPress={() => onStartRecord()}><Text>Record</Text></TouchableOpacity>
    <TouchableOpacity  onPress={() => onStopRecord()}><Text>Stop Recording</Text></TouchableOpacity>
    <TouchableOpacity  onPress={() => onStartPlay()}><Text>Play</Text></TouchableOpacity>
    <TouchableOpacity  onPress={() => onStopPlay()}><Text>Stop Playing</Text></TouchableOpacity>
  </SafeAreaView>);


}


```

**Comment by hyochan** [comment]
Have you tried our example project?
Main sourcecode is in [intro.tsx](https://github.com/dooboolab/react-native-audio-recorder-player/blob/master/Example/src/components/screen/Intro.tsx)
