### ISSUE TITLE
Document startRecorder new parameter: meteringEnabled for startRecorder

### ISSUE THREAD

**Issue by marcosPerezRubio** [dooboolab/react-native-audio-recorder-player#224]
### Version of react-native-audio-recorder-player
2.5.2

Hello!

I'm not following the template since it's not a funcional issue.

I was having issues with iOS recording on AAC format, since by default its ALAC, and I found that the signature has changed, having a second boolean parameter _meteringEnabled_ that it's not present in the documentation.

I would like to know how this works, and if its possible to add it into the documentation, since it can cause problems to other adopters of your amazing library.

I didn't have this issue in the past since I was using a previous version and only specifiying the path parameter.

Also, some other thoughs to take in consideration.
- Why is ALAC  format used by default, when aac would be portable between platforms?
- If the ALAC encoding it's mean to stay this way, it would be nice to have it explained in the documentation.

Thank you for this amazing library, 

I'm eager to help so let me know if there is something I can do.

Regards!

**Comment by hyochan** [comment]
This is updated in #191. @mynameisguy Could you kindly follow this?
