### ISSUE TITLE
Does this work for expo ?

### ISSUE THREAD

**Issue by Jsh007** [dooboolab/react-native-audio-recorder-player#228]
Hello Everyone, I'm currently in search of a sound recorder/player for an App project built with expo. If no, please recommend alternatives. Please don't tell me React-Mic-Gold because it's too expensive.

**Comment by Yassiremt** [comment]
use this one
https://docs.expo.io/versions/latest/sdk/audio/

**Comment by hyochan** [comment]
In bare workflow, yes.

**Comment by adnanaslam475** [comment]
how to convert custom expo to bareworkflow? @hyochan
