### ISSUE TITLE
Can only play on the same platform as recorded on.

### ISSUE THREAD

**Issue by JeremyBradshaw7** [dooboolab/react-native-audio-recorder-player#23]
### Version of react-native-audio-recorder-player
2.0.8

### Platforms you faced the error (IOS or Android or both?)
Both

### Expected behavior
Files are playable on both platforms.

### Actual behavior
Audio file only playable on the platform it was recorded on.

### Steps to reproduce the behavior
Standard path records .m4a on ios and .mp4 on Android, but they are only playable on that same platform (if uploaded to a server and downloaded to the other platform's app).

Is there any universal sound format that can work across platforms?

**Comment by dooboolab** [comment]
Well. As I said in `medium blog` I only supported default extension in each platform. To achieve what you are willing to, I'd prefer you to convert the audio extension in your backend server with some beautiful packages like `ffmpeg`.

**Comment by HananeAlSamrout** [comment]
change line **90** in **node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.jav**a  to
`mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
`
and line **124** in **node_modules/react-native-audio-recorder-player/ios/RNAudioRecorderPlayer.m** to
`[NSNumber numberWithInt: kAudioFormatMPEG4AAC],AVFormatIDKey,
`

and it will work on both platforms
