### ISSUE TITLE
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Boolean - This error pops up when startRecorder is called.

### ISSUE THREAD

**Issue by gaurav-bhandari-cipl** [dooboolab/react-native-audio-recorder-player#230]
### Version of react-native-audio-recorder-player

"react-native-audio-recorder-player": "^2.5.3"

### Platforms you faced the error (IOS or Android or both?)

Only Android. iOS is working fine.

### Expected behavior

Recording should start as soon as startRecorder is called.

### Actual behavior
com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.Boolean - This error pops up when startRecorder is called.

### Steps to reprodue the behabior
Using react-native : "0.63.0" & "react-native-audio-recorder-player": "^2.5.3". This error is also reproducible in Example App. This issue was being tested on OnePlus6T.

My Code : 

```
onStartAudioRecord` = async () => {
    if (Platform.OS === 'android') {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title: 'Permissions for write access',
            message: 'Give permission to your storage to write a file',
            buttonPositive: 'ok',
          },
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          console.log('You can use the storage');
        } else {
          Toast.show('Permission Denied', {
            duration: Toast.durations.LONG,
            position: Toast.positions.BOTTOM,
            shadow: true,
            animation: true,
            hideOnPress: true,
            delay: 0,
          });
          return;
        }
      } catch (err) {
        console.warn(err);
        return;
      }
    }
    await this.setState({
      recordingStatus: 'Recording',
    });
    const audioSet = {
      AudioEncoderAndroid: AudioEncoderAndroidType.DEFAULT,
      AudioSourceAndroid: AudioSourceAndroidType.MIC,
      AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
      AVNumberOfChannelsKeyIOS: 2,
      AVFormatIDKeyIOS: AVEncodingOption.aac,
    };
    const path = Platform.select({
      ios: `Audio-${new Date().toISOString()}.m4a`,
      android: `sdcard/Audio-${new Date().toISOString()}.mp4`,
    });
    const audioURI = await this.audioRecorderPlayer.startRecorder(
      path,
      audioSet,
    );
    this.audioRecorderPlayer.addRecordBackListener((e) => {
      this.setState({
        audioRecordSecs: e.current_position,
        audioRecordTime: this.audioRecorderPlayer.mmssss(
          Math.floor(e.current_position),
        ),
      });
      return;
    });
  };
```

Please take a look. Attaching a screenshot for refernce. Thanks in advance.

![AudioRecorderPlayerExample](https://user-images.githubusercontent.com/67456208/96454074-f7375800-1238-11eb-9343-130fad4aa5e6.JPEG)

**Comment by gaurav-bhandari-cipl** [comment]
Possible Unhandled Promise Rejection (id: 0):
Error : sdcard/Audio-DateIsoString.mp4 : open failed: EACCESS (Permission Denied)

After downgrading to "react-native-audio-recorder-player": "^2.4.0", this above mentioned issue was resolved but still the startRecorder function is not working properly. A warning pops up in the log which i guess is related to Permissions Storage, but i have already allowed permissions for storage. I am not getting pass the startRecorder statement and neither addRecordBackListener is called. Please see the attached screenshot and code mentioned above for reference. Thanks in Advance.


![](https://files.slack.com/files-pri/T06RQTMJA-F01D0TN5ESY/screenshot_2020-10-19_at_12.20.04_pm.png)
![Permissions](https://user-images.githubusercontent.com/67456208/96591089-7c3b7380-1304-11eb-81cf-6482dd0a9a13.JPEG)

**Comment by hyochan** [comment]
Fixed on `2.5.4`.

**Comment by lander854** [comment]
still happening on android on v.6 RC3

**Comment by Aung-Myint-Thein** [comment]
@hyochan .. when will 2.5.4 be available on npm? Strangely, one of my users is having another weird issue..

**Comment by hyochan** [comment]
Could you also try using a permission library like https://github.com/zoontek/react-native-permissions to handle your proper permission. This must be the better approach which is its focus.

**Comment by Ricardo-MT** [comment]
Try replacing this:
const audioURI = await this.audioRecorderPlayer.startRecorder(
      path,
      audioSet
    );

with this:
const audioURI = await this.audioRecorderPlayer.startRecorder(
      path,
      false,
      audioSet
    );

The function "startRecorder" now recieves 3 parameters
