### ISSUE TITLE
Example not working?

### ISSUE THREAD

**Issue by tae-at-speer** [dooboolab/react-native-audio-recorder-player#234]
### Version of react-native-audio-recorder-player
2.6.0-rc3
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Record audio and play and display time of recording.
### Actual behavior
When press record, time doesn't go up and tried file generated after stop recording and it doesn't play any sounds.
Also there is no time for the sound.

**Comment by hyochan** [comment]
It is working!
