### ISSUE TITLE
Error: sdcard/sound.mp4: open failed: EACCES (Permission denied) when targetSdkVersion = 29 set

### ISSUE THREAD

**Issue by kromsik** [dooboolab/react-native-audio-recorder-player#241]
### Version of react-native-audio-recorder-player
`"react-native-audio-recorder-player": "^2.5.4",`

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No errors

### Actual behavior
```
[Wed Nov 18 2020 16:34:32.284]  WARN     Possible Unhandled Promise Rejection (id: 0):
Error: sdcard/sound.mp4: open failed: EACCES (Permission denied)
```
### Steps to reprodue the behabior
Error happening when set `targetSdkVersion = 29` ❌
With `targetSdkVersion = 28` everything is fine!  ✅

Other code is untouched, but I can share just for reference

```typescript
const AudioRecorder: React.FC<Props> = ({ visible, onClose, onDone }: Props) => {
  const [recording, setRecording] = React.useState<boolean>(false)
  const [time, setTime] = React.useState<string | undefined>('00:00:00')
  const rec = React.useRef<AudioRecorderPlayer>()

  React.useEffect(() => {
    if (visible) {
      rec.current = new AudioRecorderPlayer()
    } else {
      rec.current = undefined
    }
  }, [visible])

  const onStartRecord = async () => {
    if (rec.current) {
      await rec.current.startRecorder()
      rec.current.addRecordBackListener((e: RecordEvent) => {
        setTime(rec.current?.mmssss(Math.floor(e.current_position)))
        return
      })
    }
  }

  const onStopRecord = async () => {
    const result = await rec.current?.stopRecorder()
    rec.current?.removeRecordBackListener()
    if (result) {
      onDone(result)
      onClose()
    }
  }

  const toggleRecording = () => {
    if (recording) {
      onStopRecord()
    } else {
      onStartRecord()
    }
    setRecording((prev) => !prev)
  }

  const iconName = !recording ? 'mic-outline' : 'stop-circle-outline'

  return (
    <Modal visible={visible} transparent animationType="fade" animated>
      <View
        style={{
          flex: 1,
          backgroundColor: 'rgba(0,0,0,0.5)',
        }}
      >
        <ModalBox visible>
          <View
            style={{
              backgroundColor: 'transparent',
              marginHorizontal: 12,
              marginTop: 12,
              alignItems: 'flex-end',
            }}
          >
            <TouchableOpacity onPress={onClose} hitSlop={hitSlop} disabled={recording}>
              <Icon
                name={'close-outline'}
                width={24}
                fill={!recording ? StyleGuide.colors.brand : StyleGuide.colors.grey}
                height={24}
              />
            </TouchableOpacity>
          </View>
          <View
            style={{
              flex: 1,
              justifyContent: 'center',
              alignItems: 'center',
              backgroundColor: 'transparent',
            }}
          >
            {!recording && (
              <Text style={{ marginBottom: 12 }} category="h6">
                Начать запись
              </Text>
            )}
            {recording && (
              <>
                <PlayingIndicator />
                <Text style={{ marginBottom: 12 }} category="h6">
                  {time}
                </Text>
              </>
            )}
            <TouchableOpacity
              onPress={toggleRecording}
              style={{
                width: 48,
                height: 48,
                borderRadius: 48 / 2,
                borderWidth: 1,
                justifyContent: 'center',
                alignItems: 'center',
                borderColor: StyleGuide.colors.brandDark,
              }}
            >
              <Icon name={iconName} width={24} height={24} fill={StyleGuide.colors.brandDark} />
            </TouchableOpacity>
          </View>
        </ModalBox>
      </View>
    </Modal>
  )
}
```

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.VIBRATE" />
```

Google says: 
`Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29` https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by kromsik** [comment]
But upgrading to Api level 29 is required by Google to release an update for the App!

**Comment by kromsik** [comment]
Dear all! This is kind critical, because API level of 29 is now required by Google.

**Comment by Ryxar** [comment]
Hello same error here. Pretty Critical, we will not be able to push in Prod

**Comment by robertqin86** [comment]
Hi the solution is to add the following to the Android manifest, `application` tag for API level 29. 

`android:requestLegacyExternalStorage="true"`. 

See [this](https://stackoverflow.com/questions/58430070/android-apiv29-filenotfoundexception-eacces-permission-denied) for details

**Comment by kromsik** [comment]
> Hi the solution is to add the following to the Android manifest, `application` tag for API level 29. 
> 
> 
> 
> `android:requestLegacyExternalStorage="true"`. 
> 
> 
> 
> See [this](https://stackoverflow.com/questions/58430070/android-apiv29-filenotfoundexception-eacces-permission-denied) for details

Worked for me. Thanks!

**Comment by hyochan** [comment]
This is available now starting from version `3.0.0-beta.3` 🙌 without `requestLegacyExternalStorage` if you want to use the `default` path.

**Comment by mrigo** [comment]
Hey! For API Level 30 is required "MANAGE_EXTERNAL_STORAGE" permission and the android:requestLegacyExternalStorage doesn't work anymore!
This is also critical!!

**Comment by alishah514** [comment]
> Hi the solution is to add the following to the Android manifest, `application` tag for API level 29.
> 
> `android:requestLegacyExternalStorage="true"`.
> 
> See [this](https://stackoverflow.com/questions/58430070/android-apiv29-filenotfoundexception-eacces-permission-denied) for details

What if we want to increase the TargetSDKVersion to 31 or 32 and use this audio recorder feature as well? Is it possible to use this on new android devices?

**Comment by alishah514** [comment]
I am testing the App on Android 12 with the targetSDKversion 31 but it's showing me the error `Error: sdcard/sound.mp3: open failed: EACCES (Permission denied)`
I have tried many solutions as suggested by many developers like adding `requestLegacyExternalStorage` permission in AndroidManifest file and also giving permission of MANAGE_EXTERNAL_STORAGE but still the error is same.

After decreasing the targetSDKversion to 29. App is working fine on Android 12 but since we can't upload it on Play Store, it's not useful and also some features becomes. 

What should I do to make this feature work on Android 12 and above without decreasing the TargetSDKversion?
Can anybody help?

**Comment by mjefim** [comment]
I am running into the same issues. @alishah514 and others, did anyoune find a solution?
