### ISSUE TITLE
Player stops except for playing next audio track in a playlist when the app is in background.

### ISSUE THREAD

**Issue by abhishektiwari-kiwi** [dooboolab/react-native-audio-recorder-player#247]
### Steps to reprodue the behavior : 1. Create a playlist of some audios, 2. Implement playing logic sequentially, 3. Put the app in background while playing any audio. 4. once the currently playing audio track finishes, next one won't launch(only when the app is in background)

Note: It's android specific.

**Comment by stylder** [comment]
.
