### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by DavidWilliamBalbino** [dooboolab/react-native-audio-recorder-player#25]
Sometimes I save my code and try to play a new audio it appears on my console "You can use the camera" ... And when I try to press the pause, it returns me this error

![46744427_193766478230532_4579644419937927168_n](https://user-images.githubusercontent.com/19325395/48850717-60ce3380-ed90-11e8-922c-1ee1dc7f213e.png)

**Comment by DavidWilliamBalbino** [comment]
And to give a help, before returning this error when clicking the pause. It shows this in the console "Already recording" and then this "uri: undefined"

**Comment by dooboolab** [comment]
I don't quite understand the situation because you've referenced the `camera`. Could you be more specific how you reproduced the error? Like what was your step?
