### ISSUE TITLE
Does the audio player work for one path at a time?

### ISSUE THREAD

**Issue by hmhm2292** [dooboolab/react-native-audio-recorder-player#254]
### Version of react-native-audio-recorder-player
version 2.6.0
### Platforms you faced the error (IOS or Android or both?)
Both IOS and Android

### Expected behavior
when using startPlayer() in a flatlist of items, when one audio path is playing and while one is playing if i start another player I am expecting other player to play.
Expecting multiple players to play at the same time.
### Actual behavior

when using startPlayer() in a flatlist of items, when one audio path is playing and while one is playing if i start another player the other player does not play.

### Steps to reproduce the behavior
Create a Flatlist with each item having its own audioRecordPlayer

**Comment by Balthazar33** [comment]
Hi @hmhm2292 , how did you solve this? Can you please share how you've implemented it?

**Comment by xbaldiq** [comment]
i'm also looking for this solution
