### ISSUE TITLE
send audio by formdata

### ISSUE THREAD

**Issue by camiloibarrayepes** [dooboolab/react-native-audio-recorder-player#26]
### Version of react-native-audio-recorder-player
2.0.8

### Platforms you faced the error (IOS or Android or both?)
both

when recording and playing an audio everything works fine, when I try to send it by formData, it's coming with a type of audio "audio/ x-m4a"

the way I'm sending it is (in iOS)

formData.append("incident[incident_description_attributes[file_name]]", {
      uri: this.state.resultAudio,
      name: 'test.m4a',
      type: 'audio/m4a',
    })

resultAudio is: const result = await this.audioRecorderPlayer.stopRecorder();

but when I receive the audio, it arrives in the following way

"file": {
               "url": "....",
               "name": "test.m4a",
               "content_type": "audio/x-m4a",
               "upload_date": "Dec  5, 2018",
               "size": "3 MB"
           }

uri is ok, but the file does not play

**Comment by dooboolab** [comment]
Try the below code which I am using.
```
      const uriParts = uri.split('.');
      const fileType = uriParts[uriParts.length - 1];

      const formData: any = new FormData();
      const audioFile: any = {
        uri,
        name: `audio.{fileType}`,
        type: `audio/x-${fileType}`,
      };
      formData.append('inputAudio', audioFile);
```

**Comment by camiloibarrayepes** [comment]
didn't work :( , i see that the solution that you give me is similar, because you get the extention (m4a or mp4), but the problem is when I send it by formData, the type of the file arrives "audio/x-m4a" and doesn't allow to play the sound, thanks again

**Comment by dooboolab** [comment]
I am confused. Didn't you want to upload? and you are now talking about playing sound which works differently in each platform.

**Comment by camiloibarrayepes** [comment]
when I try to send my audio file, the file breaks, and can not play the audio, when I receive the audio file I get the type "audio/x-m4a", but the size is correct, but I can not to play and download the audio.

this is how the file arrives to the server

"file": {
"url": "....",
"name": "test.m4a",
"content_type": "audio/x-m4a",
"upload_date": "Dec 5, 2018",
"size": "3 MB"
}

**Comment by dooboolab** [comment]
Looks bit awkward to me because I'm using this quite well in my production app which is `COONI`. What react-native version are you at?

**Comment by camiloibarrayepes** [comment]
0.52.0 is my current react native version, 

How do you send your audio files to the server in your application?

**Comment by dooboolab** [comment]
I've already shared the working code above. You should test if your server correctly getting this.

**Comment by ede-sous** [comment]
Hello, I have the same issue, did you find any solution for this issue? @camiloibarrayepes

**Comment by AmirDiafi** [comment]
Try this one:

```
const data = new FormData()
          const recordFileType = Platform.select({
            ios: 'm4a',
            android: 'mp4',
          })
          const uri =
            Platform.OS === 'android'
              ? recordFile
              : recordFile.replace('file://', '')
          console.log('recordFileType', uri)
          data.append('file', {
            uri,
            type: `sound/x-${recordFileType}`,
            name: `sound.${recordFileType}`,
          })
```

**Comment by ravis-farooq** [comment]
Unable to Play Recorded Audio from Browser in react-native-audio-recorder-player


I attempted to play an audio file that was recorded from a browser  and then uploaded to the server.
Using the link provided (https://inf-minio.dreamkashmir.com/influnairedev/9d8c894c-d8fc-4d5b-8520-85bebae86f0c.aac) within a React Native application utilizing the react-native-audio-recorder-player library. However, despite multiple attempts, the audio file failed to play successfully.
