### ISSUE TITLE
Recorder taking too long to stop on Android

### ISSUE THREAD

**Issue by vitorverasm** [dooboolab/react-native-audio-recorder-player#271]
### Expected behavior
Should stop recording in the moment we call `stopRecorder()`.

### Actual behavior
In android when I try to do long recordings(1 minute at least) and I call `stopRecorder()` it continues recording for almost 10seconds before it finishes recording. On iOS this behavior doesn't happen no matter what the duration of the recording.

I want to know if there's something that I can do to solve this, other than upgrade react native because my project uses  **React Native 0.59.10**.

### Steps to reproduce the behavior
react-native-audio-recorder-player: ^2.5.3
react-native: 0.59.10

- [use example App](https://github.com/dooboolab/react-native-audio-recorder-player/tree/master/Example)
- Record for 1 minute and stop calling `stopRecorder`

### Logs
```
2021-03-30 12:31:12.741 28006-28059/com.fortics.szchat W/MediaRecorder: mediarecorder went away with unhandled events
```

**Comment by vitorverasm** [comment]
Figured out what my problem was. My component was having a huge state object, and on every millisecond it updates with the current duration of the recording. This was causing bad performance issues.

So I cut down some of the state and cleaned up the structure and the slow stopRecording went away.

**Comment by Joshmatjjen** [comment]
@vitorverasm .... Please can u share the code on how u fix this... Cause i am also experiencing it too...

**Comment by vitorverasm** [comment]
@Joshmatjjen what I did was to refactor the component decreasing the state object and removing unwanted re-renders. My problem wasn't with the library itself, the problem was on my code structure.

**Comment by Joshmatjjen** [comment]
@vitorverasm ... Thanks for the info... Please can u share an example code u used....
