### ISSUE TITLE
After stopRecord() the audio file cannot be found in the path that was returned

### ISSUE THREAD

**Issue by DiegoOno** [dooboolab/react-native-audio-recorder-player#274]
### Version of react-native-audio-recorder-player
2.6.2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Finish recording -> load the file -> send to a s3 bucket

### Actual behavior
The file isn't found, so can't be load.

### Steps to reprodue the behabior
I just followed the steps to record a sound and tested it on IOS simulator.

I also checked the permission to use microphone. 
One hypothesis is that there is a problem with the storage, but I am new to iOS development.
This problem only occurred on IOS. On android the sound record works fine.

![Screenshot from 2021-04-16 15-54-02](https://user-images.githubusercontent.com/24476314/115071084-2b2fc500-9ecc-11eb-9868-7ed30f7e086e.png)
![Screenshot from 2021-04-16 15-54-35](https://user-images.githubusercontent.com/24476314/115071088-2c60f200-9ecc-11eb-92b4-284c30645ad6.png)
![Screenshot from 2021-04-16 15-55-07](https://user-images.githubusercontent.com/24476314/115071089-2cf98880-9ecc-11eb-9b56-4af94484a973.png)

In the HandleSendAudio method I read the file, so in this step this warning appears.

**Comment by DiegoOno** [comment]
I found the solution to my problem. In the path returned by stopRecord() it is necessary to remove 'file://'.

**Comment by ravis-farooq** [comment]
> I found the solution to my problem. In the path returned by stopRecord() it is necessary to remove 'file://' to read the file in IOS.

Thanks alot it is working.
