### ISSUE TITLE
Record audio in mp3 format

### ISSUE THREAD

**Issue by LilianeAquino** [dooboolab/react-native-audio-recorder-player#28]
Hello, guys!!!

I need a solution to record the mp3 audio. Your library only allows recording in mp4 format, which is not supported by the IBM Speech to Text api. I'm developing an android app with react native.

**Comment by aelarassi** [comment]
> Hello, guys!!!
> 
> I need a solution to record the mp3 audio. Your library only allows recording in mp4 format, which is not supported by the IBM Speech to Text api. I'm developing an android app with react native.

_________________________________________

Hi @LilianeAquino ,

it's a temporary solution : 

1/ go to :  **project/node_modules/react-native-audio-recorder-player**

2/ open class **RNAudioRecorderPlayerModule.java**

3/ search to :   **final private static String FILE_LOCATION = "/sdcard/sound.mp4";**

4/ replace to : **final private static String FILE_LOCATION = "/sdcard/sound.mp3";**
 
Finally build a new app on your device

**Comment by traxx10** [comment]
What about ios?

**Comment by amorino** [comment]
Any update on this?

**Comment by zuhairnaqi** [comment]
What about iOS?

**Comment by luatvudinh** [comment]
Any update?

**Comment by zuhairnaqi** [comment]
I used a `.aac` format to use on both Android and iOS platforms.

**Comment by luatvudinh** [comment]
> I used a `.aac` format to use on both Android and iOS platforms.

I used this to solve the problem.

```
const cacheDir = RNFS.CachesDirectoryPath;
const path = Platform.select({
      ios: generateRandomId() + '.m4a',
      android: `${cacheDir}/${generateRandomId()}.mp3`,
});
audioRecorder.startRecorder(path).then();
```

**Comment by ArjunKarki** [comment]
> 

I did the same and convert to bas64 and send to backend. when the backend site decoded the bas64, the out is not mp3  
format, it is something else.Now backend is asking to send valid mp3.

**Comment by ArjunKarki** [comment]
> I did the same and convert to bas64 and send to backend. when the backend site decoded the bas64, the out is not mp3
format, it is something else.Now backend is asking to send valid mp3.

**Comment by zuhairnaqi** [comment]
> I used a `.aac` format to use on both Android and iOS platforms.

The reason I used the aac file is it play on both platforms

**Comment by therealtgd** [comment]
+1 on this issue

**Comment by muhsin-k** [comment]
@therealtgd Did you able to solve this issue?
