### ISSUE TITLE
temporarily record the audio and delete?

### ISSUE THREAD

**Issue by harguus** [dooboolab/react-native-audio-recorder-player#29]
### Android

Hello, how would I temporarily record the audio and delete it?

**Comment by hyochan** [comment]
We've not yet supported the `deletion`. However, you can overwrite it. This should be implemented tough.

**Comment by harguus** [comment]
Okay, no problem like that. It will always overwrite the file.

Thank you!

**Comment by hyochan** [comment]
Closes #195

**Comment by faizantariq1** [comment]
Hi @hyochan still delete functionality not supported? As i want to store many audios with timestamps. overriding will be difficult.
