### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [dooboolab/react-native-audio-recorder-player#3]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by dooboolab** [comment]
@mansya Yes. Why not? I'll love to see your wok!

**Comment by mansya** [comment]
I have design logo for this project. what do you think sir ? which one do you like ?
![react native audio recorder player](https://user-images.githubusercontent.com/33461607/44388186-abea6780-a551-11e8-800f-e21f1f3d73d0.png)

**Comment by dooboolab** [comment]
@mansya Everything looks great!! awesome! It is just the matter of colors. Saya mau nomor tujuh dan nomor delapan. However, I prefer anything. I would be better if you choose one for me.

Also, it will be greate to use this icon in [flutter_sound](https://github.com/dooboolab/flutter_sound) project too. What do you think?

**Comment by dooboolab** [comment]
@mansya Thank you! I will mention your name in my repo as a logo supporter. I'll use your icon as whatever you want.

**Comment by mansya** [comment]
thank you because you want to mention my name in your project. By the way, I'm sorry for being late in replying. I had a long trip yesterday. and I have sent you [Pull Requests](https://github.com/dooboolab/react-native-audio-recorder-player/pull/7). you can see it. All files about this icon have been uploaded to this [Drive](https://drive.google.com/open?id=1f89V07GvJjd79OWhGCY6Jfc_Avuj3lYY).

**Comment by dooboolab** [comment]
@mansya Awesome!! I've just merged this. Great great work!

**Comment by mansya** [comment]
hi sir. I made a little change in the font. because in the previous font is too less neat and clear to read on a small scale.

**Comment by hyochan** [comment]
![Peek 2021-05-04 20-50](https://user-images.githubusercontent.com/27461460/116999369-7c3c1780-ad1a-11eb-90ff-5aa7141e7565.gif)
