### ISSUE TITLE
Error: setDataSource failed.

### ISSUE THREAD

**Issue by harguus** [dooboolab/react-native-audio-recorder-player#30]
### onStartPlay
console.log('onStartPlay');
    const msg = await audioRecorderPlayer.startPlayer();
    console.log(msg);
    this.audioRecorderPlayer.addPlayBackListener((e) => {
      if (e.current_position === e.duration) {
        console.log('finished');
        this.audioRecorderPlayer.stopPlayer();
      }
      this.setState({
        currentPositionSec: e.current_position,
        currentDurationSec: e.duration,
        playTime: this.audioRecorderPlayer.mmssss(Math.floor(e.current_position)),
        duration: this.audioRecorderPlayer.mmssss(Math.floor(e.duration)),
      });
      return;
    });

### Steps to reprodue the behabior
onStartRecord and then onStartPlayer

the permissions are given

### Error code:

Error: setDataSource failed.
Error: setDataSource failed.
    at createErrorFromErrorData (blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:2007:17)
    at blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:1959:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:2510:18)
    at blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:2257:18
    at MessageQueue.__guard (blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:2414:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/484e680f-425f-48c2-be69-d8cbd47c9c8f:2256:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:72:58

**Comment by hyochan** [comment]
I can't truly understand the problem. Could you be more concise and clear?

**Comment by harguus** [comment]
English:

was trying to write the audio to a specific path other than the default, and this error appears: "Error: setDataSource failed". by default the audio path is: "file: ///sdcard/sound.mp4" wanted to save in another corner.
for now I will leave the pattern, but how can I change the way and avoid this error?

Portuguese:

Estava tentando gravar o áudio em um caminho específico diferente do padrão, e esse erro aparece: "Error: setDataSource failed". por padrão o caminho do áudio é: "file:///sdcard/sound.mp4" queria salvar em outro canto.
por enquanto vou deixar no padrão, mas como posso mudar o caminho e evitar esse erro?

**Comment by hyochan** [comment]
@harguus I think `android` won't let you save the file to exact path because of `permission` issue. If I am understanding correctly, `ios` path is relative to root of your app's folder where `android` is relative to system folder. Therefore, you should create some folder with permission of use `accesible` folder like `download`, `sdcard` .. etc.

**Comment by harguus** [comment]
Okay, I'll look at this later. thanks for the support!
