### ISSUE TITLE
Can't install package 

### ISSUE THREAD

**Issue by montaserfzy** [dooboolab/react-native-audio-recorder-player#31]
i am trying to install the packages, but not installing  

react-native-cli: `2.0.1`
react-native: `0.57.8`
npm: `6.6.0`
yarn: `1.12.3`

command : `npm install react-native-audio-recorder-player --save`

<img width="533" alt="screen shot 2019-02-02 at 11 13 31 pm" src="https://user-images.githubusercontent.com/8565425/52169406-6f49ab80-2740-11e9-9504-7cc073891e56.png">

**Comment by hyochan** [comment]
You should link the library. This is native dependent!
