### ISSUE TITLE
TypeError: Cannot read property 'startRecorder' of undefined

### ISSUE THREAD

**Issue by Manouli** [dooboolab/react-native-audio-recorder-player#33]
I can see the audio player when I press play it says its undefined. 
It works just fine on Android. 
I have posted a picture to showcase what it is doing.

I have checked everywhere (all the files) to see if that is a linking issue but its not.

### Version of react-native-audio-recorder-player
Version of player: 2.1.2
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Start recording
### Actual behavior
![image](https://user-images.githubusercontent.com/6332957/53977287-99580a00-4100-11e9-843c-d006184b16ec.png)
### Steps to reproduce the behaviour
Pretty standard steps as described.
Only difference I guess is our react native version.

I am using  "react-native": "0.58.6",

**Comment by Manouli** [comment]
All of a sudden it started working. I ll close this for now.

**Comment by PedroGaletti** [comment]
Same problem!

**Comment by fawadtariq** [comment]
Same problem! Does anyone have any information about this?
I am receiving a warning instead of an error.

![image](https://user-images.githubusercontent.com/18026360/59510031-1c40eb80-8ecc-11e9-8e17-95258f7b35d7.png)

**Comment by simformsolutions** [comment]
We are also facing the same issue.

**Comment by saadrehman013** [comment]
I facing this similar issue. Any help would be appreciated.
React version: 16.8.6
React native version: 0.60.5
Plugin version: 2.2.4
Ios version: 12.2

![Screenshot 2019-09-05 at 10 26 36 AM](https://user-images.githubusercontent.com/11928832/64314233-c1e59180-cfc7-11e9-91db-46408262044d.png)

**Comment by phillipb** [comment]
FYI, this should not be closed. Still facing this issue React native 0.61.5, ios 13

**Comment by shanike** [comment]
Have the same issue here
