### ISSUE TITLE
No re-render component when using startPlayer(). 

### ISSUE THREAD

**Issue by maxakak1998** [dooboolab/react-native-audio-recorder-player#67]

**Comment by maxakak1998** [comment]
I have the button and the text like this : 
![image](https://user-images.githubusercontent.com/50696626/58316550-f9c43100-7e3d-11e9-87b0-52d783528a0e.png)
When user click on the button,the isLoading state is set to true and then i will trigger the onPress func and call start func. 
![image](https://user-images.githubusercontent.com/50696626/58316624-2aa46600-7e3e-11e9-9c7b-5ba0c1fc23c3.png)
At this time, isLoading is true, but my text is not re-rendered
And then the asyn func named play is called:
![image](https://user-images.githubusercontent.com/50696626/58316714-62aba900-7e3e-11e9-9628-d5a8ff4b4509.png)
And final i set false to isLoading.
The problem that it works perfectly with Sound lib, but it cant with this lib because it will wait for startPlayer() get the reponse then component will be re-renderer.
Hope you help !

**Comment by hyochan** [comment]
I am not quite sure what you are trying to do here. I hope you provide a more clearer example(maybe with some screenshot).

**Comment by maxakak1998** [comment]
Please closed this post, i did the trick and it works now !
