### ISSUE TITLE
Audio Recorder Player PodSpec Failed

### ISSUE THREAD

**Issue by robert589** [dooboolab/react-native-audio-recorder-player#71]
### Version of react-native-audio-recorder-player
2.1.4 

### Platforms you faced the error (IOS or Android or both?)
I try to add manually the dependencies to my podfile
`pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player/ios'`

### Expected behavior
Supposed to work 

### Actual behavior
`Analyzing dependencies
Fetching podspec for `RNAudioRecorderPlayer` from `../node_modules/react-native-audio-recorder-player/ios`
[!] The `RNAudioRecorderPlayer` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.`

**Comment by robert589** [comment]
`
Pod::Spec.new do |s|
  s.name         = "RNAudioRecorderPlayer"
  s.version      = "1.0.0"
  s.summary      = "RNAudioRecorderPlayer"
  s.description  = <<-DESC
                  RNAudioRecorderPlayer
                   DESC
  s.homepage     = ""
  s.license      = "MIT"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "author" => "author@domain.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/author/RNAudioRecorderPlayer.git", :tag => "master" }
  s.source_files  = "RNAudioRecorderPlayer/**/*.{h,m}"
  s.requires_arc = true


  s.dependency "React"
  #s.dependency "others"

end

  `

it is the <<-DESC 
supposed tobe there?

**Comment by robert589** [comment]
Pod::Spec.new do |s|
  s.name         = "RNAudioRecorderPlayer"
  s.version      = "1.0.0"
  s.summary      = "RNAudioRecorderPlayer"
  s.description  = "RNAudioRecorderPlayer"
  s.homepage     = "https://github.com/dooboolab/react-native-audio-recorder-player" 
  s.license      = "MIT"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "author" => "author@domain.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/author/RNAudioRecorderPlayer.git", :tag => "master" }
  s.source_files  = "RNAudioRecorderPlayer/**/*.{h,m}"
  s.requires_arc = true


  s.dependency "React"
  #s.dependency "others"

end

**Comment by robert589** [comment]
> 
Pod::Spec.new do |s|
  s.name         = "RNAudioRecorderPlayer"
  s.version      = "1.0.0"
  s.summary      = "RNAudioRecorderPlayer"
  s.description  = "RNAudioRecorderPlayer"
  s.homepage     = "https://github.com/dooboolab/react-native-audio-recorder-player" 
  s.license      = "MIT"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "author" => "author@domain.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/author/RNAudioRecorderPlayer.git", :tag => "master" }
  s.source_files  = "RNAudioRecorderPlayer/**/*.{h,m}"
  s.requires_arc = true


  s.dependency "React"
  #s.dependency "others"

end

  
I think this can be the solution

**Comment by robert589** [comment]
Hi, i just try with my solution in previous message and it works, please modify accordingly

**Comment by hyochan** [comment]
@robert589 Thanks for trying it out!! Could you please give a `PR` for your work? I'd like this to be done by the founder.

**Comment by NRamirezCR** [comment]
I fixed this by moving Podfile out of the ios directory, and updating the file references:

```
require "json"

package = JSON.parse(File.read(File.join(__dir__, "/package.json")))

Pod::Spec.new do |s|
  s.name           = "RNAudioRecorderPlayer"
  s.version        = package["version"]
  s.summary        = "This is a react-native link module for audio recorder and player. This is not a playlist audio module and this library provides simple recorder and player functionalities for both android and ios platforms. This only supports default file extension for each platform. This module can also handle file from url."
  s.author         = "doobolab <doobolab@gmail.com> (https://github.com/dooboolab)"

  s.homepage       = "https://github.com/dooboolab/react-native-audio-recorder-player"

  s.license        = "MIT"

  s.ios.deployment_target = "7.0"

  s.source         = { :git => "https://github.com/dooboolab/react-native-audio-recorder-player.git", :tag => "#{s.version}" }
  s.source_files   = "ios/**/*.{h,m}"
  s.preserve_paths = "**/*.js"
  # s.requires_arc   = true

  s.dependency "React"
end
```

**Comment by NRamirezCR** [comment]
somebody already submitted a PR for this #106 3 hours ago
