### ISSUE TITLE
Playing twice

### ISSUE THREAD

**Issue by maxakak1998** [dooboolab/react-native-audio-recorder-player#77]
### Steps to reprodue the behabior

![image](https://user-images.githubusercontent.com/50696626/59563914-39132580-906a-11e9-8425-48775e8dfbd5.png)

Before this code, i have played the audio from URI and then i pause it. Then i played another one in phone's storage but it still played the previous audio from URI.

I logged the console above  and the result was "Player resumed"

![image](https://user-images.githubusercontent.com/50696626/59563948-b9398b00-906a-11e9-8f8f-7453dd4ed1ff.png)

Please help, thanks in advance !

**Comment by hyochan** [comment]
Try to `stopPlayer` beforehand to release the player holding the previous audio file.

**Comment by maxakak1998** [comment]
> Try to `stopPlayer` beforehand to release the player holding the previous audio file.

Thanks i will try it again cuz i have tried it before but no result.
