### ISSUE TITLE
File upload's type is GP, not mp4/m4a although file's tag is mp4/m4a, and can't play this audio from url 

### ISSUE THREAD

**Issue by Hieutt1704** [dooboolab/react-native-audio-recorder-player#78]
### React-native 0.59.5

**Comment by hyochan** [comment]
I hope you could provide more example to help you out.

**Comment by Hieutt1704** [comment]
Here is audio's url: http://118.70.180.81:8055/UserAudio/74fca23d-fc54-4b5d-9213-1d220abaf22a/2019/6/1560826688hccqb0.m4a when i post the audio file recored. I converted this file to base64 and saw: 
![61719298_383691719162980_3339387727484289024_n](https://user-images.githubusercontent.com/38338250/59651956-06764380-91b6-11e9-9b63-22eecfe265e4.jpg)
You need a tool dowload to dowload this file,that counld't be dowloaded from browser

**Comment by Hieutt1704** [comment]
I tried react-native-audio and it work perpectly

**Comment by hyochan** [comment]
@Hieutt1704 I hope you can provide us clearer example so that I can do some work on improving our module.

**Comment by Hieutt1704** [comment]
Here is the code record audio: 
**onStartRecord = async () => {
    const result = await this.audioRecorderPlayer.startRecorder();
    this.setState({ uri_audio: result, startRecord: true })
    this.audioRecorderPlayer.addRecordBackListener(e => {
      if (this.state.recordSecs == 12) {
        this.onStopRecord();
        Utils.showToast(I18n.t("limit_record"));
      } else
        this.setState({
          recordSecs: (e.current_position / 1000).toFixed(0),
        });
      return;
    });
  };

  onStopRecord = async () => {
    const { recordSecs, uri_audio, startRecord } = this.state
    if (!startRecord) return
    await this.audioRecorderPlayer.stopRecorder();
    this.audioRecorderPlayer.removeRecordBackListener()
    const content = {
      currentPositionSec: 0,
      recordSecs: 0,
      startRecord: false,
      duration: recordSecs,
      uri_audio,
      startPlay: false,
      playTime: 0,
    }
    this.setState(content)
  };**
Here is the code,that I post audio file to server: 
**
const  dataAudio = {
 uri: this.state.uri_audio,
 type: Platform.OS == 'ios' ? 'audio/m4a' : 'audio/mp4',
 name: Platform.OS == 'ios' ? 'sound.m4a' : 'sound.mp4',
}
const data = new FormData()
data.append("content", dataAudio)
res = await Apis.createAudio(data)
**

**Comment by hyochan** [comment]
You now can pass various variables when `recording` from `2.3.0`. Please try this.
