### ISSUE TITLE
Make Compatible with androidx

### ISSUE THREAD

**Issue by JeremyBradshaw7** [dooboolab/react-native-audio-recorder-player#81]
### Version of react-native-audio-recorder-player
2.1.4 

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Builds without issue

### Actual behavior
Build errors

### Steps to reproduce the behavior
Just build and get errors:

> Task :react-native-audio-recorder-player:compileDebugJavaWithJavac FAILED
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:18: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:19: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:20: error: package android.support.v4.content does not exist
import android.support.v4.content.PermissionChecker;
                                 ^
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:69: error: cannot find symbol
                  ActivityCompat.checkSelfPermission(reactContext, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED &&
                  ^
  symbol:   variable ActivityCompat
  location: class RNAudioRecorderPlayerModule
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:70: error: cannot find symbol
                  ActivityCompat.checkSelfPermission(reactContext, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED
                  ^
  symbol:   variable ActivityCompat
  location: class RNAudioRecorderPlayerModule
/Users/jeremybradshaw/ccf-android/node_modules/react-native-audio-recorder-player/android/src/main/java/com/dooboolab/RNAudioRecorderPlayerModule.java:73: error: cannot find symbol
        ActivityCompat.requestPermissions(getCurrentActivity(), new String[]{
        ^
  symbol:   variable ActivityCompat
  location: class RNAudioRecorderPlayerModule
6 errors

**Comment by hyochan** [comment]
Could you try to install `PR` in #82 and come back?
