### ISSUE TITLE
Could not resolve all artifacts for configuration ':react-native-audio-recorder-player:classpath'.

### ISSUE THREAD

**Issue by usamaazam10** [dooboolab/react-native-audio-recorder-player#89]
### Version of react-native-audio-recorder-player
react-native-audio-recorder-player: 2.2.0
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
record voice after installing package.
### Actual behavior
it appearing error after installing package and then running project.

<img width="1057" alt="Screenshot 2019-07-15 at 3 48 10 PM" src="https://user-images.githubusercontent.com/30794533/61211642-8cd06780-a719-11e9-89de-b3dc1d224dc3.png">

### Steps to reprodue the behabior
just install package and re run project by react-native run-android

**Comment by kvrscream** [comment]
Hi...

I solved this Issue adding a google() above jcenter() into /node_modules/react-native-audio-recorder-player/android/build.gradle

![Captura de Tela 2019-07-15 às 10 29 00](https://user-images.githubusercontent.com/12921095/61219812-6562a600-a6eb-11e9-900b-533d08549322.png)

**Comment by chirhotec** [comment]
@kvrscream that worked for me too

**Comment by hyochan** [comment]
Closed via `2.2.1`.
