### ISSUE TITLE
undefined is not an object (evaluating 'this.audioRecorderPlayer.startRecorder')

### ISSUE THREAD

**Issue by Harsh2402** [dooboolab/react-native-audio-recorder-player#9]
### Version of react-native-audio-recorder-player
"react-native-audio-recorder-player": "^2.0.8",
"react-native": "^0.56.1",

### Platforms you faced the error (IOS or Android or both?)
- Android

I have imported the library and used the methods for the recording but getting the following type of error while start recording.

undefined is not an object (evaluating 'this.audioRecorderPlayer.startRecorder')

**Comment by dooboolab** [comment]
@Harsh2402 Could you try our example project then come back again? Feels like this is `react-native` linking issue.
