### ISSUE TITLE
Uri Has two // insist of three

### ISSUE THREAD

**Issue by mhdsoft** [dooboolab/react-native-audio-recorder-player#97]
when I use startRecorder() function return uri . but this uri is not usable for Upload.
my solution is to use replace function like below
const newUri=result.replace('file://','file:///')
and its work fine on android 
my question is this trick works on ios or Not .

**Comment by hyochan** [comment]
Why not grabbing actual `uri` when your `stopRecorder`?

**Comment by hyochan** [comment]
I think this issue depends on the `device`.
