### ISSUE TITLE
TypeError: Cannot read property 'stopRecorder' of undefined

### ISSUE THREAD

**Issue by simformsolutions** [dooboolab/react-native-audio-recorder-player#98]
I can see the audio player when I press play it says it is undefined.
It works just fine on Android.

I have checked everywhere (all the files) to see if that is a linking issue and found that it is not showing up in products in pod folder (Attached screenshot below) but not sure it is happening due to the same or not.

Version of react-native-audio-recorder-player: 2.2.2

Platforms you faced the error (IOS or Android or both?)
IOS

Expected behavior
Start recording

![Screen Shot 2019-08-05 at 6 04 50 PM](https://user-images.githubusercontent.com/8736329/62465318-369c9480-b7ac-11e9-8c3f-d029146627c9.png)

**Comment by chandanrai95** [comment]
you got some solution?

**Comment by simformsolutions** [comment]
Nope still looking for solution.

**Comment by aliotadi** [comment]
any solution?

**Comment by simformsolutions** [comment]
Nope switched to the react-native audio toolkit and it is working fine.

**Comment by hyochan** [comment]
Please try `2.2.3` and come back for current issue.

**Comment by aliotadi** [comment]
now i don't get the undefined error but still i cann't record anything in ios, recorder will start but i'ts not working as expected, the 'addRecordBackListener's current_position is always 0

**Comment by hyochan** [comment]
Please try `2.3.0`.

**Comment by simformsolutions** [comment]
Hi, @hyochan  I have tried v2.3.0 and the good news is that I am not facing undefined error but recording seems broken as I am also getting current_position as 0 always in 'addRecordBackListener'.

**Comment by hyochan** [comment]
@simformsolutions Which platform are you facing this? Did you also try `example` project in repo?
