### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')

### ISSUE THREAD

**Issue by chandanrai95** [dooboolab/react-native-audio-recorder-player#99]
### Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')

### Steps to reprodue the behabior

**Comment by aliotadi** [comment]
same problem here...

**Comment by hyochan** [comment]
I think this is a `podspec` problem. I think this will be fixed in `2.2.3` and please come back after trying it out.

**Comment by abir4u** [comment]
Using current version: **react-native-audio-recorder-player@^2.4.3**

The same issue still exists.
Please help.

Issue detected for the following Functions:
**startRecorder
startPlayer**

**Comment by maxckelly** [comment]
Same issue - My current version is `"react-native-audio-recorder-player": "^2.5.2",`

and happening with startRecorder.

**Comment by Harikasai999** [comment]
hi,
this issue still exists in `"react-native-audio-recorder-player": "^2.5.3"`.  How can i fix it??

**Comment by shanike** [comment]
Try this
```
const onStartRecord = async () => {
        const path = Platform.select({
            ios: 'hello.m4a',
            android: 'sdcard/hello.mp4', // should give extra dir name in android. Won't grant permission to the first level of dir.
        });
        const audioSet = {
            AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
            AudioSourceAndroid: AudioSourceAndroidType.MIC,
            AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
            AVNumberOfChannelsKeyIOS: 2,
            AVFormatIDKeyIOS: AVEncodingOption.aac,
        };
        const meteringEnabled = false;

        let uri;
        
        try {
            uri = await this.audioRecorderPlayer.startRecorder(path, meteringEnabled, audioSet);
        } catch (e) { console.log("ERR audioRecorderPlayer.startRecorder: ", e) }
        audioRecorderPlayer.addRecordBackListener((e) => {
            setState(state => ({
                ...state,
                recordSecs: e.current_position,
                recordTime: audioRecorderPlayer.mmssss(
                    Math.floor(e.current_position),
                ),
            }));
            return;
        });
        console.log("uri: ", uri);
    };
```

**Comment by shanike** [comment]
and there's an example here
https://github.com/dooboolab/react-native-audio-recorder-player/blob/master/Example/src/components/screen/Intro.tsx

**Comment by QasimJaffry** [comment]
Hi. It still is giving the same issue.

**Comment by castor55** [comment]
> and there's an example here,
> part of the git repository of the react-native-audio-recorder-player npm package
> https://github.com/dooboolab/react-native-audio-recorder-player/blob/master/Example/src/components/screen/Intro.tsx

404 error.

**Comment by castor55** [comment]
@shanike Why did you close this issue? I still see the same issue on 3.0.8.

**Comment by bicccio** [comment]
Same here  "react-native-audio-recorder-player": "^3.1.0",

**Comment by shanike** [comment]
... go to the repository's home page... from a quick look, they changed the folders, https://github.com/dooboolab/react-native-audio-recorder-player


> > and there's an example here,
> > part of the git repository of the react-native-audio-recorder-player npm package
> > https://github.com/dooboolab/react-native-audio-recorder-player/blob/master/Example/src/components/screen/Intro.tsx
> 
> 404 error.

**Comment by shanike** [comment]
didnt close anything idk

> @shanike Why did you close this issue? I still see the same issue on 3.0.8.

**Comment by falcon977** [comment]
@shanike The same error occurs with me.
[TypeError: undefined is not an object (evaluating '_this.audioRecorderPlayer.startRecorder')] and I am using react-native-audio-recorder-player 3.1.0 and I didn't see any efficient solution while reading this forum. Could you please explain me what exactly should I do to resolve that ? 
Thanks

**Comment by shanike** [comment]
@falcon977 
Hi, it's been a while back so I don't remember really what I did. I might have used a different library.
Anyway, this was my insight about the matter:

> Try this onStartRecord func
> 
> ```
> const onStartRecord = async () => {
>         const path = Platform.select({
>             ios: 'hello.m4a',
>             android: 'sdcard/hello.mp4', // should give extra dir name in android. Won't grant permission to the first level of dir.
>         });
>         const audioSet = {
>             AudioEncoderAndroid: AudioEncoderAndroidType.AAC,
>             AudioSourceAndroid: AudioSourceAndroidType.MIC,
>             AVEncoderAudioQualityKeyIOS: AVEncoderAudioQualityIOSType.high,
>             AVNumberOfChannelsKeyIOS: 2,
>             AVFormatIDKeyIOS: AVEncodingOption.aac,
>         };
>         const meteringEnabled = false;
> 
>         let uri;
>         
>         try {
>             uri = await this.audioRecorderPlayer.startRecorder(path, meteringEnabled, audioSet);
>         } catch (e) { console.log("ERR audioRecorderPlayer.startRecorder: ", e) }
>         audioRecorderPlayer.addRecordBackListener((e) => {
>             setState(state => ({
>                 ...state,
>                 recordSecs: e.current_position,
>                 recordTime: audioRecorderPlayer.mmssss(
>                     Math.floor(e.current_position),
>                 ),
>             }));
>             return;
>         });
>         console.log("uri: ", uri);
>     };
> ```
> 
> and imports are from react-native-audio-recorder-player package and from react-native:
> 
> ```
> import { Button, Platform } from 'react-native';
> import AudioRecorderPlayer, { AudioEncoderAndroidType, AudioSourceAndroidType, AVEncoderAudioQualityIOSType, AVEncodingOption } from 'react-native-audio-recorder-player';
> ```

**Comment by hyochan** [comment]
> @shanike The same error occurs with me.
> [TypeError: undefined is not an object (evaluating '_this.audioRecorderPlayer.startRecorder')] and I am using react-native-audio-recorder-player 3.1.0 and I didn't see any efficient solution while reading this forum. Could you please explain me what exactly should I do to resolve that ?
> Thanks

Since there seems to be a war here, I've just run the `Example` project and check the consequences. First time the `iOS` build failed and I've just removed the `flipper` and it works again.

<img width="1399" alt="Screen Shot 2021-07-27 at 10 42 28 AM" src="https://user-images.githubusercontent.com/27461460/127081441-53c60587-1e7b-4e99-9a2c-df98517ad88d.png">

In android everything works fine. Please try the example project in the `repo`!

**Comment by hyochan** [comment]
> @shanike The same error occurs with me.
> [TypeError: undefined is not an object (evaluating '_this.audioRecorderPlayer.startRecorder')] and I am using react-native-audio-recorder-player 3.1.0 and I didn't see any efficient solution while reading this forum. Could you please explain me what exactly should I do to resolve that ?

I think we need more information. I've also tried `example` in m1 processor but the same thing failed so I've made an update https://github.com/hyochan/react-native-audio-recorder-player/commit/2a3f7b6c3a7f433d8b65688bbe97c51b515083be.

[Stackoverflow](https://stackoverflow.com/questions/65364886/react-native-on-apple-silicon-m1-the-linked-library-libpods-projectname-a-is) helped me fix the build.

**Comment by fukemy** [comment]
any solution here?

**Comment by akram-chopdawg** [comment]
why this issues is closed we still facing in
  "react-native-audio-recorder-player": "^3.5.3",

**Comment by shanike** [comment]
> > @shanike The same error occurs with me.
> > [TypeError: undefined is not an object (evaluating '_this.audioRecorderPlayer.startRecorder')] and I am using react-native-audio-recorder-player 3.1.0 and I didn't see any efficient solution while reading this forum. Could you please explain me what exactly should I do to resolve that ?
> 
> I think we need more information. I've also tried `example` in m1 processor but the same thing failed so I've made an update [2a3f7b6](https://github.com/hyochan/react-native-audio-recorder-player/commit/2a3f7b6c3a7f433d8b65688bbe97c51b515083be).
> 
> [Stackoverflow](https://stackoverflow.com/questions/65364886/react-native-on-apple-silicon-m1-the-linked-library-libpods-projectname-a-is) helped me fix the build.

Hi thank you for addressing the problem. It's been a while and I'm not into it anymore. I hope this problem has a solution. Have a great month

**Comment by Dlozlami** [comment]
This issue has yet to be solved.

**Comment by AnswerX** [comment]
I had the same issue, and I checked `apps/mobile/native/package.json` did't add `"react-native-audio-recorder-player": "3.6.12"`, then I remove the node_modules, and did npm install again
